// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/analyze/Analyze.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Analyze;

public class Analyze : global::DripSharp.SqlTrellis.Statement.Statement {
private global::DripSharp.SqlTrellis.Schema.Table table = null!;

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<T> statementVisitor, S context) {
return statementVisitor.visit(this, context);
}

public virtual global::DripSharp.SqlTrellis.Schema.Table getTable() {
return this.table;
}

public virtual void setTable(global::DripSharp.SqlTrellis.Schema.Table table) {
this.table = table;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat("ANALYZE ", this.table.ToString());
}

public virtual global::DripSharp.SqlTrellis.Statement.Analyze.Analyze withTable(global::DripSharp.SqlTrellis.Schema.Table table) {
this.setTable(table);
return this;
}
}
