// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/parser/feature/Feature.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Parser.Feature;

public sealed class Feature {
[global::DripSharp.Runtime.JavaEnumNameAttribute("select")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature select = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectGroupBy")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectGroupBy = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectGroupByGroupingSets")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectGroupByGroupingSets = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectHaving")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectHaving = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectInto")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(4)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectInto = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("limit")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(5)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature limit = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("limitNull")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(6)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature limitNull = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("limitAll")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(7)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature limitAll = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("limitOffset")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(8)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature limitOffset = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("offset")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(9)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature offset = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("offsetParam")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(10)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature offsetParam = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("fetch")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(11)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature fetch = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("fetchFirst")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(12)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature fetchFirst = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("fetchNext")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(13)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature fetchNext = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("join")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(14)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature join = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinOuterSimple")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(15)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinOuterSimple = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinSimple")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(16)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinSimple = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinRight")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(17)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinRight = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinNatural")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(18)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinNatural = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinFull")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(19)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinFull = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinLeft")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(20)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinLeft = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinCross")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(21)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinCross = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinOuter")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(22)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinOuter = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinSemi")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(23)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinSemi = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinInner")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(24)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinInner = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinStraight")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(25)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinStraight = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinApply")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(26)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinApply = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinWindow")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(27)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinWindow = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("joinUsingColumns")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(28)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature joinUsingColumns = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("skip")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(29)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature skip = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("first")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(30)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature first = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("top")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(31)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature top = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("optimizeFor")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(32)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature optimizeFor = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectUnique")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(33)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectUnique = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("distinct")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(34)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature distinct = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("distinctOn")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(35)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature distinctOn = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("orderBy")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(36)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature orderBy = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("orderByNullOrdering")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(37)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature orderByNullOrdering = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForUpdate")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(38)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForUpdate = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForShare")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(39)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForShare = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForKeyShare")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(40)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForKeyShare = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForNoKeyUpdate")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(41)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForNoKeyUpdate = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForUpdateOfTable")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(42)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForUpdateOfTable = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForUpdateWait")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(43)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForUpdateWait = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForUpdateNoWait")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(44)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForUpdateNoWait = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForUpdateSkipLocked")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(45)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForUpdateSkipLocked = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insert")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(46)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insert = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertFromSelect")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(47)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertFromSelect = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertModifierPriority")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(48)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertModifierPriority = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertModifierIgnore")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(49)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertModifierIgnore = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertUseSet")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(50)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertUseSet = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertUseDuplicateKeyUpdate")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(51)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertUseDuplicateKeyUpdate = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertReturningAll")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(52)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertReturningAll = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertReturningExpressionList")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(53)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertReturningExpressionList = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("insertValues")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(54)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature insertValues = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("values")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(55)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature __field_values = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("tableStatement")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(56)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature tableStatement = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("update")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(57)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature update = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("updateFrom")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(58)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature updateFrom = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("updateJoins")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(59)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature updateJoins = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("updateUseSelect")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(60)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature updateUseSelect = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("updateOrderBy")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(61)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature updateOrderBy = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("updateLimit")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(62)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature updateLimit = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("updateReturning")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(63)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature updateReturning = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("delete")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(64)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature delete = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("deleteJoin")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(65)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature deleteJoin = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("deleteTables")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(66)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature deleteTables = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("deleteLimit")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(67)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature deleteLimit = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("deleteOrderBy")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(68)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature deleteOrderBy = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("deleteReturningExpressionList")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(69)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature deleteReturningExpressionList = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("upsert")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(70)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature upsert = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("merge")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(71)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature merge = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("alterTable")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(72)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature alterTable = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("alterSequence")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(73)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature alterSequence = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("alterView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(74)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature alterView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("refreshMaterializedView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(75)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature refreshMaterializedView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("refreshMaterializedWithDataView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(76)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature refreshMaterializedWithDataView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("refreshMaterializedWithNoDataView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(77)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature refreshMaterializedWithNoDataView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("alterViewReplace")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(78)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature alterViewReplace = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("alterIndex")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(79)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature alterIndex = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("analyze")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(80)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature analyze = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("truncate")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(81)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature truncate = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("execute")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(82)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature execute = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("executeExec")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(83)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature executeExec = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("executeCall")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(84)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature executeCall = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("executeExecute")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(85)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature executeExecute = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("executeStatement")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(86)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature executeStatement = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("executeStatementImmediate")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(87)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature executeStatementImmediate = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("executeUsing")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(88)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature executeUsing = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("replace")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(89)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature replace = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("drop")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(90)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature drop = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropTable")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(91)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropTable = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropIndex")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(92)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropIndex = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(93)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropSchema")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(94)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropSchema = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropSequence")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(95)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropSequence = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropTableIfExists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(96)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropTableIfExists = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropIndexIfExists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(97)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropIndexIfExists = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropViewIfExists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(98)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropViewIfExists = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropSchemaIfExists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(99)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropSchemaIfExists = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("dropSequenceIfExists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(100)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature dropSequenceIfExists = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createSchema")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(101)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createSchema = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(102)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createViewForce")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(103)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createViewForce = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createViewTemporary")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(104)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createViewTemporary = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createOrReplaceView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(105)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createOrReplaceView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createViewMaterialized")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(106)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createViewMaterialized = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createViewWithComment")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(107)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createViewWithComment = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTable")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(108)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTable = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTableUnlogged")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(109)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTableUnlogged = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTableCreateOptionStrings")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(110)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTableCreateOptionStrings = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTableTableOptionStrings")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(111)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTableTableOptionStrings = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTableIfNotExists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(112)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTableIfNotExists = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTableRowMovement")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(113)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTableRowMovement = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTableFromSelect")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(114)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTableFromSelect = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createIndex")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(115)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createIndex = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createSequence")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(116)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createSequence = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createSynonym")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(117)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createSynonym = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createTrigger")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(118)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createTrigger = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("commit")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(119)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature commit = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("comment")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(120)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature comment = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("commentOnTable")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(121)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature commentOnTable = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("commentOnColumn")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(122)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature commentOnColumn = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("commentOnView")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(123)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature commentOnView = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("describe")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(124)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature describe = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("desc")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(125)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature desc = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("explain")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(126)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature explain = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("show")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(127)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature show = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("showTables")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(128)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature showTables = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("showColumns")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(129)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature showColumns = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("showIndex")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(130)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature showIndex = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("use")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(131)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature use = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("grant")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(132)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature grant = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("function")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(133)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature function = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createFunction")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(134)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createFunction = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("createProcedure")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(135)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature createProcedure = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("functionalStatement")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(136)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature functionalStatement = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("block")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(137)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature block = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("declare")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(138)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature declare = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("set")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(139)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature set = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("reset")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(140)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature reset = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("pivot")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(141)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature pivot = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("unpivot")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(142)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature unpivot = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("pivotXml")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(143)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature pivotXml = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("setOperation")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(144)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature setOperation = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("setOperationUnion")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(145)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature setOperationUnion = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("setOperationIntersect")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(146)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature setOperationIntersect = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("setOperationExcept")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(147)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature setOperationExcept = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("setOperationMinus")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(148)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature setOperationMinus = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("withItem")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(149)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature withItem = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("withItemRecursive")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(150)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature withItemRecursive = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("lateralSubSelect")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(151)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature lateralSubSelect = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("valuesList")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(152)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature valuesList = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("tableFunction")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(153)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature tableFunction = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("jdbcParameter")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(154)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature jdbcParameter = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("jdbcNamedParameter")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(155)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature jdbcNamedParameter = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("exprLike")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(156)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature exprLike = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("exprSimilarTo")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(157)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature exprSimilarTo = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("kSqlWindow")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(158)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature kSqlWindow = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("oracleOldJoinSyntax")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(159)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature oracleOldJoinSyntax = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("oraclePriorPosition")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(160)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature oraclePriorPosition = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("oracleHint")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(161)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature oracleHint = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("oracleHierarchicalExpression")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(162)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature oracleHierarchicalExpression = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("oracleOrderBySiblings")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(163)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature oracleOrderBySiblings = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("mySqlHintStraightJoin")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(164)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature mySqlHintStraightJoin = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("mysqlSqlCacheFlag")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(165)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature mysqlSqlCacheFlag = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("mysqlCalcFoundRows")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(166)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature mysqlCalcFoundRows = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("selectForXmlPath")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(167)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature selectForXmlPath = new global::DripSharp.SqlTrellis.Parser.Feature.Feature();

[global::DripSharp.Runtime.JavaEnumNameAttribute("allowSquareBracketQuotation")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(168)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature allowSquareBracketQuotation = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(false);

[global::DripSharp.Runtime.JavaEnumNameAttribute("allowPostgresSpecificSyntax")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(169)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature allowPostgresSpecificSyntax = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(false);

[global::DripSharp.Runtime.JavaEnumNameAttribute("allowComplexParsing")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(170)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature allowComplexParsing = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(true);

[global::DripSharp.Runtime.JavaEnumNameAttribute("allowUnsupportedStatements")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(171)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature allowUnsupportedStatements = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(false);

[global::DripSharp.Runtime.JavaEnumNameAttribute("timeOut")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(172)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature timeOut = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(8000);

[global::DripSharp.Runtime.JavaEnumNameAttribute("allowBackslashEscapeCharacter")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(173)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature allowBackslashEscapeCharacter = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(false);

[global::DripSharp.Runtime.JavaEnumNameAttribute("allowUnparenthesizedSubSelects")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(174)]
public static readonly global::DripSharp.SqlTrellis.Parser.Feature.Feature allowUnparenthesizedSubSelects = new global::DripSharp.SqlTrellis.Parser.Feature.Feature(false);

private readonly object value = null!;

private readonly bool configurable = default;

private Feature() {
this.value = default!;
this.configurable = false;
}

private Feature(object value) {
this.value = value;
this.configurable = true;
}

public object getDefaultValue() {
return this.value;
}

public bool isConfigurable() {
return this.configurable;
}

public static Feature[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<Feature>();
public static Feature valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<Feature>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
