// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/piped/CallPipeOperator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Piped;

public class CallPipeOperator : global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator {
private global::DripSharp.SqlTrellis.Statement.Select.TableFunction tableFunction = null!;

private global::DripSharp.SqlTrellis.Expression.Alias alias = null!;

public CallPipeOperator(global::DripSharp.SqlTrellis.Statement.Select.TableFunction tableFunction, global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.tableFunction = tableFunction;
this.alias = alias;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.TableFunction getTableFunction() {
return this.tableFunction;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.CallPipeOperator setTableFunction(global::DripSharp.SqlTrellis.Statement.Select.TableFunction tableFunction) {
this.tableFunction = tableFunction;
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Alias getAlias() {
return this.alias;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.CallPipeOperator setAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.alias = alias;
return this;
}

public override global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
builder.Append("|> CALL ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.tableFunction));
if ((this.alias != default!)) {
builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.alias));
}
return builder;
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Piped.PipeOperatorVisitor<T, S> visitor, S context) {
return visitor.visit(this, context);
}
}
