// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/piped/DropPipeOperator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Piped;

public class DropPipeOperator : global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator {
private global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> columns = null!;

public DropPipeOperator(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> columns) {
this.columns = columns;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> getColumns() {
return this.columns;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.DropPipeOperator setColumns(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> columns) {
this.columns = columns;
return this;
}

public virtual bool containsAll(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> c) {
return global::DripSharp.Runtime.JavaCompat.ContainsAll(this.columns, global::DripSharp.Runtime.JavaCompat.CastObjects(c));
}

public virtual global::DripSharp.SqlTrellis.Schema.Column get(int index) {
return global::DripSharp.Runtime.JavaCompat.ListGet(this.columns, index);
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> addExpression(global::DripSharp.SqlTrellis.Schema.Column expression) {
return global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Schema.Column>(this.columns.addExpression(expression));
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> addExpressions(params global::DripSharp.SqlTrellis.Schema.Column[] expressions) {
return global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Schema.Column>(this.columns.addExpressions(expressions));
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> addExpressions(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> expressions) {
return global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Schema.Column>(this.columns.addExpressions(expressions));
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> withExpressions(params global::DripSharp.SqlTrellis.Schema.Column[] expressions) {
return global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Schema.Column>(this.columns.withExpressions(expressions));
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> withExpressions(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> expressions) {
return global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Schema.Column>(this.columns.withExpressions(expressions));
}

public virtual K accept<K, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<K> expressionVisitor, S context) {
return this.columns.accept((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<K>)(expressionVisitor), context);
}

public virtual void trimToSize() {
(this.columns).TrimExcess();
}

public virtual bool addAll(int index, global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> c) {
return global::DripSharp.Runtime.JavaCompat.ListAddAll(this.columns, index, c);
}

public virtual bool retainAll(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> c) {
return global::DripSharp.Runtime.JavaCompat.RetainAll(this.columns, global::DripSharp.Runtime.JavaCompat.CastObjects(c));
}

public virtual global::DripSharp.Runtime.JavaStream<global::DripSharp.SqlTrellis.Schema.Column> parallelStream() {
return global::DripSharp.Runtime.JavaCompat.Stream(this.columns);
}

public virtual bool addAll(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> c) {
return global::DripSharp.Runtime.JavaCompat.AddAll(this.columns, c);
}

public virtual int indexOf(global::DripSharp.SqlTrellis.Schema.Column o) {
return global::DripSharp.Runtime.JavaCompat.ListIndexOf(this.columns, o);
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
((global::DripSharp.SqlTrellis.Expression.Expression)(this.columns)).accept((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor));
}

public virtual void forEach(global::System.Action<global::DripSharp.SqlTrellis.Schema.Column> action) {
global::DripSharp.Runtime.JavaCompat.ForEach(this.columns, action);
}

public virtual int lastIndexOf(global::DripSharp.SqlTrellis.Schema.Column o) {
return global::DripSharp.Runtime.JavaCompat.ListLastIndexOf(this.columns, o);
}

public virtual global::DripSharp.Runtime.JavaStream<global::DripSharp.SqlTrellis.Schema.Column> stream() {
return global::DripSharp.Runtime.JavaCompat.Stream(this.columns);
}

public virtual global::System.Collections.Generic.IEnumerable<global::DripSharp.SqlTrellis.Schema.Column> spliterator() {
return this.columns;
}

public virtual global::DripSharp.SqlTrellis.Schema.Column set(int index, global::DripSharp.SqlTrellis.Schema.Column element) {
return global::DripSharp.Runtime.JavaCompat.ListSet(this.columns, index, element);
}

public virtual void sort(global::System.Collections.Generic.IComparer<global::DripSharp.SqlTrellis.Schema.Column> c) {
global::DripSharp.Runtime.JavaCompat.SortList(this.columns, c);
}

public virtual void ensureCapacity(int minCapacity) {
global::DripSharp.Runtime.JavaCompat.EnsureCapacity(this.columns, minCapacity);
}

public virtual bool remove(global::DripSharp.SqlTrellis.Schema.Column o) {
return global::DripSharp.Runtime.JavaCompat.CollectionRemove(this.columns, o);
}

public virtual object[] toArray() {
return global::DripSharp.Runtime.JavaCompat.ToObjectArray(this.columns);
}

public virtual global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Schema.Column> iterator() {
return global::DripSharp.Runtime.JavaCompat.Iterator(this.columns);
}

public virtual T[] toArray<T>(global::System.Func<int, T[]> generator) {
return global::DripSharp.Runtime.JavaCompat.CollectionToArray(this.columns, generator);
}

public virtual bool add(global::DripSharp.SqlTrellis.Schema.Column column) {
return global::DripSharp.Runtime.JavaCompat.Add(this.columns, column);
}

public virtual global::DripSharp.Runtime.JavaListIterator<global::DripSharp.SqlTrellis.Schema.Column> listIterator(int index) {
return global::DripSharp.Runtime.JavaCompat.ListIterator(this.columns, index);
}

public virtual void replaceAll(global::System.Func<global::DripSharp.SqlTrellis.Schema.Column, global::DripSharp.SqlTrellis.Schema.Column> @operator) {
global::DripSharp.Runtime.JavaCompat.ReplaceAll(this.columns, @operator);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Schema.Column> subList(int fromIndex, int toIndex) {
return global::DripSharp.Runtime.JavaCompat.SubList(this.columns, fromIndex, toIndex);
}

public virtual bool removeAll(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> c) {
return global::DripSharp.Runtime.JavaCompat.RemoveAll(this.columns, global::DripSharp.Runtime.JavaCompat.CastObjects(c));
}

public virtual bool isEmpty() {
return global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.columns);
}

public virtual void clear() {
(this.columns).Clear();
}

public virtual bool contains(global::DripSharp.SqlTrellis.Schema.Column o) {
return global::DripSharp.Runtime.JavaCompat.CollectionContains(this.columns, o);
}

public virtual global::DripSharp.SqlTrellis.Schema.Column remove(int index) {
return global::DripSharp.Runtime.JavaCompat.ListRemove(this.columns, index);
}

public virtual bool removeIf(global::System.Func<global::DripSharp.SqlTrellis.Schema.Column, bool> filter) {
return global::DripSharp.Runtime.JavaCompat.RemoveIf(this.columns, filter);
}

public virtual T[] toArray<T>(T[] a) {
return global::DripSharp.Runtime.JavaCompat.CollectionToArray(this.columns, a);
}

public virtual void add(int index, global::DripSharp.SqlTrellis.Schema.Column element) {
global::DripSharp.Runtime.JavaCompat.ListAdd(this.columns, index, element);
}

public virtual int size() {
return global::DripSharp.Runtime.JavaCompat.CollectionCount(this.columns);
}

public virtual global::DripSharp.Runtime.JavaListIterator<global::DripSharp.SqlTrellis.Schema.Column> listIterator() {
return global::DripSharp.Runtime.JavaCompat.ListIterator(this.columns);
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Piped.PipeOperatorVisitor<T, S> visitor, S context) {
return visitor.visit(this, context);
}

public override global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
builder.Append("|> ").Append("DROP ");
this.columns.appendTo(builder).Append("\n");
return builder;
}
}
