// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/piped/FromQuery.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Piped;

public class FromQuery : global::DripSharp.SqlTrellis.Statement.Select.Select {
private bool usingFromKeyword = true;

private global::DripSharp.SqlTrellis.Statement.Select.FromItem fromItem = null!;

private global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.LateralView> lateralViews = default!;

private global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.Join> joins = default!;

private readonly global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> pipeOperators = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator>();

public FromQuery(global::DripSharp.SqlTrellis.Statement.Select.FromItem fromItem) {
this.fromItem = fromItem;
}

public FromQuery(global::DripSharp.SqlTrellis.Statement.Select.FromItem fromItem, bool usingFromKeyword) {
this.fromItem = fromItem;
this.usingFromKeyword = usingFromKeyword;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.FromItem getFromItem() {
return this.fromItem;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery setFromItem(global::DripSharp.SqlTrellis.Statement.Select.FromItem fromItem) {
this.fromItem = fromItem;
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery with(global::DripSharp.SqlTrellis.Statement.Select.FromItem fromItem) {
return this.setFromItem(fromItem);
}

public virtual bool isUsingFromKeyword() {
return this.usingFromKeyword;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.LateralView> getLateralViews() {
return this.lateralViews;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery setLateralViews(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.LateralView> lateralViews) {
this.lateralViews = lateralViews;
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery addLateralViews(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.LateralView> lateralViews) {
if ((this.lateralViews == default!)) {
this.lateralViews = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.LateralView>(lateralViews);
} else {
global::DripSharp.Runtime.JavaCompat.AddAll(this.lateralViews, lateralViews);
}
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery addLateralViews(params global::DripSharp.SqlTrellis.Statement.Select.LateralView[] lateralViews) {
return this.addLateralViews(global::DripSharp.Runtime.JavaCompat.AsList<global::DripSharp.SqlTrellis.Statement.Select.LateralView>(lateralViews));
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.Join> getJoins() {
return this.joins;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery setJoins(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.Join> joins) {
this.joins = joins;
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery addJoins(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.Join> joins) {
if ((this.joins == default!)) {
this.joins = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.Join>(joins);
} else {
global::DripSharp.Runtime.JavaCompat.AddAll(this.joins, joins);
}
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery addJoins(params global::DripSharp.SqlTrellis.Statement.Select.Join[] joins) {
return this.addJoins(global::DripSharp.Runtime.JavaCompat.AsList<global::DripSharp.SqlTrellis.Statement.Select.Join>(joins));
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery setUsingFromKeyword(bool usingFromKeyword) {
this.usingFromKeyword = usingFromKeyword;
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery with(bool usingFromKeyword) {
return this.setUsingFromKeyword(usingFromKeyword);
}

public virtual global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> getPipeOperators() {
return this.pipeOperators;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery add(global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator @operator) {
global::DripSharp.Runtime.JavaCompat.Add(this.pipeOperators, @operator);
return this;
}

public virtual void add(int index, global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator element) {
global::DripSharp.Runtime.JavaCompat.ListAdd(this.pipeOperators, index, element);
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator remove(int index) {
return global::DripSharp.Runtime.JavaCompat.ListRemove(this.pipeOperators, index);
}

public virtual bool remove(object o) {
return global::DripSharp.Runtime.JavaCompat.CollectionRemove(this.pipeOperators, o);
}

public virtual void clear() {
(this.pipeOperators).Clear();
}

public virtual bool addAll(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> c) {
return global::DripSharp.Runtime.JavaCompat.AddAll(this.pipeOperators, c);
}

public virtual bool addAll(int index, global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> c) {
return global::DripSharp.Runtime.JavaCompat.ListAddAll(this.pipeOperators, index, c);
}

public virtual bool removeAll(global::System.Collections.Generic.ICollection<object> c) {
return global::DripSharp.Runtime.JavaCompat.RemoveAll(this.pipeOperators, global::DripSharp.Runtime.JavaCompat.CastObjects(c));
}

public virtual bool retainAll(global::System.Collections.Generic.ICollection<object> c) {
return global::DripSharp.Runtime.JavaCompat.RetainAll(this.pipeOperators, global::DripSharp.Runtime.JavaCompat.CastObjects(c));
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> subList(int fromIndex, int toIndex) {
return global::DripSharp.Runtime.JavaCompat.SubList(this.pipeOperators, fromIndex, toIndex);
}

public virtual void forEach(global::System.Action<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> action) {
global::DripSharp.Runtime.JavaCompat.ForEach(this.pipeOperators, action);
}

public virtual global::System.Collections.Generic.IEnumerable<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> spliterator() {
return this.pipeOperators;
}

public virtual bool removeIf(global::System.Func<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator, bool> filter) {
return global::DripSharp.Runtime.JavaCompat.RemoveIf(this.pipeOperators, filter);
}

public virtual void replaceAll(global::System.Func<global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator, global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator> @operator) {
global::DripSharp.Runtime.JavaCompat.ReplaceAll(this.pipeOperators, @operator);
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.FromQuery with(global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator @operator) {
return this.add(@operator);
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator get(int index) {
return global::DripSharp.Runtime.JavaCompat.ListGet(this.pipeOperators, index);
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator set(int index, global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator element) {
return global::DripSharp.Runtime.JavaCompat.ListSet(this.pipeOperators, index, element);
}

public virtual int size() {
return global::DripSharp.Runtime.JavaCompat.CollectionCount(this.pipeOperators);
}

public virtual bool isEmpty() {
return global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.pipeOperators);
}

public virtual bool contains(object o) {
return global::DripSharp.Runtime.JavaCompat.CollectionContains(this.pipeOperators, o);
}

public virtual int indexOf(object o) {
return global::DripSharp.Runtime.JavaCompat.ListIndexOf(this.pipeOperators, o);
}

public virtual int lastIndexOf(object o) {
return global::DripSharp.Runtime.JavaCompat.ListLastIndexOf(this.pipeOperators, o);
}

public virtual object[] toArray() {
return global::DripSharp.Runtime.JavaCompat.ToObjectArray(this.pipeOperators);
}

public virtual T[] toArray<T>(T[] a) {
return global::DripSharp.Runtime.JavaCompat.CollectionToArray(this.pipeOperators, a);
}

public override global::DripSharp.SqlTrellis.Expression.Alias getAlias() {
return default!;
}

public override void setAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot getPivot() {
return default!;
}

public override void setPivot(global::DripSharp.SqlTrellis.Statement.Select.Pivot pivot) {}

public override global::DripSharp.SqlTrellis.Statement.Select.UnPivot getUnPivot() {
return default!;
}

public override void setUnPivot(global::DripSharp.SqlTrellis.Statement.Select.UnPivot unpivot) {}

public override global::DripSharp.SqlTrellis.Statement.Select.SampleClause getSampleClause() {
return default!;
}

public override global::DripSharp.SqlTrellis.Statement.Select.FromItem setSampleClause(global::DripSharp.SqlTrellis.Statement.Select.SampleClause sampleClause) {
return default!;
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.FromItemVisitor<T> fromItemVisitor, S context) {
return fromItemVisitor.visit(this, context);
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T> selectVisitor, S context) {
return selectVisitor.visit(this, context);
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Piped.FromQueryVisitor<T, S> fromQueryVisitor, S context) {
return fromQueryVisitor.visit(this, context);
}

public override global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
if (((base.withItemsList != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(base.withItemsList)))) {
builder.Append("WITH ");
for (global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> iter = global::DripSharp.Runtime.JavaCompat.Iterator(base.withItemsList); iter.HasNext(); ) {
global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement> withItem = iter.Next()!;
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(withItem));
if (iter.HasNext()) {
builder.Append(",");
}
builder.Append(" ");
}
}
if (this.usingFromKeyword) {
builder.Append("FROM ");
}
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.fromItem)).Append("\n");
if ((this.lateralViews != default!)) {
foreach (global::DripSharp.SqlTrellis.Statement.Select.LateralView lateralView in this.lateralViews) {
builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(lateralView));
}
}
if ((this.joins != default!)) {
foreach (global::DripSharp.SqlTrellis.Statement.Select.Join join in this.joins) {
if (join.isSimple()) {
builder.Append(", ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(join));
} else {
builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(join));
}
}
}
foreach (global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator @operator in this.pipeOperators) {
@operator.appendTo(builder);
}
return builder;
}
}
