// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/piped/SelectPipeOperator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Piped;

public class SelectPipeOperator : global::DripSharp.SqlTrellis.Statement.Piped.PipeOperator {
private readonly string operatorName = null!;

private readonly string modifier = null!;

private readonly global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> selectItems = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>>();

public SelectPipeOperator(string operatorName, global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression> selectItem, string modifier) {
this.operatorName = operatorName;
this.modifier = modifier;
global::DripSharp.Runtime.JavaCompat.Add(this.selectItems, selectItem);
}

public virtual string getOperatorName() {
return this.operatorName;
}

public virtual string getModifier() {
return this.modifier;
}

public virtual global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> getSelectItems() {
return this.selectItems;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.SelectPipeOperator add(global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression> selectItem) {
global::DripSharp.Runtime.JavaCompat.Add(this.selectItems, selectItem);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Piped.SelectPipeOperator with(global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression> selectItem) {
return this.add(selectItem);
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Piped.PipeOperatorVisitor<T, S> visitor, S context) {
return visitor.visit(this, context);
}

public override global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
builder.Append("|> ").Append(this.operatorName);
if (((this.modifier != default!) && !((this.modifier.Length == 0)))) {
builder.Append(" ").Append(this.modifier);
}
int i = 0;
foreach (var selectItem in this.selectItems) {
builder.Append(((i++ > 0) ? ", " : " ")).Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(selectItem));
}
builder.Append("\n");
return builder;
}
}
