// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/alter/sequence/AlterSequence.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Alter.Sequence;

public class AlterSequence : global::DripSharp.SqlTrellis.Statement.Statement {
public global::DripSharp.SqlTrellis.Schema.Sequence sequence = null!;

public virtual global::DripSharp.SqlTrellis.Schema.Sequence getSequence() {
return this.sequence;
}

public virtual void setSequence(global::DripSharp.SqlTrellis.Schema.Sequence sequence) {
this.sequence = sequence;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<T> statementVisitor, S context) {
return statementVisitor.visit(this, context);
}

public override string ToString() {
string sql;
sql = global::DripSharp.Runtime.JavaCompat.Concat("ALTER SEQUENCE ", this.sequence);
return sql;
}

public virtual global::DripSharp.SqlTrellis.Statement.Alter.Sequence.AlterSequence withSequence(global::DripSharp.SqlTrellis.Schema.Sequence sequence) {
this.setSequence(sequence);
return this;
}

public virtual void accept<TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<TWildcard0_0> statementVisitor) {
this.accept<TWildcard0_0, object>(statementVisitor, (object)default!);
}
}
