// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/parser/SimpleCharStream.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Parser;

public class SimpleCharStream {
public const bool staticFlag = false;

public int bufpos = -1;

protected internal int[] bufline = null!;

protected internal int[] bufcolumn = null!;

protected internal int column = 0;

protected internal int line = 1;

protected internal bool prevCharIsCR = false;

protected internal bool prevCharIsLF = false;

protected internal global::DripSharp.SqlTrellis.Parser.Provider inputStream = null!;

protected internal char[] buffer = null!;

protected internal int maxNextCharInd = 0;

protected internal int inBuf = 0;

protected internal int tabSize = 1;

protected internal bool trackLineColumn = true;

protected internal int totalCharsRead = 0;

protected internal int absoluteTokenBegin = 0;

internal int bufsize = default;

internal int available = default;

internal int tokenBegin = default;

private bool isStringProvider = default;

public SimpleCharStream(global::DripSharp.SqlTrellis.Parser.Provider dstream, int startline, int startcolumn, int buffersize) {
this.inputStream = dstream;
this.isStringProvider = (dstream is global::DripSharp.SqlTrellis.Parser.StringProvider);
this.line = startline;
this.column = (startcolumn - 1);
if (this.isStringProvider) {
int bs = ((global::DripSharp.SqlTrellis.Parser.StringProvider)(this.inputStream!))._string.Length;
this.available = (this.bufsize = bs);
this.bufline = new int[bs];
this.bufcolumn = new int[bs];
} else {
this.available = (this.bufsize = buffersize);
this.buffer = new char[buffersize];
this.bufline = new int[buffersize];
this.bufcolumn = new int[buffersize];
}
}

public SimpleCharStream(global::DripSharp.SqlTrellis.Parser.Provider dstream, int startline, int startcolumn) : this(dstream, startline, startcolumn, 4096) {

}

public SimpleCharStream(global::DripSharp.SqlTrellis.Parser.Provider dstream) : this(dstream, 1, 1, 4096) {

}

public virtual int getTabSize() {
return this.tabSize;
}

public virtual void setTabSize(int i) {
this.tabSize = i;
}

public int getAbsoluteTokenBegin() {
return this.absoluteTokenBegin;
}

protected internal virtual void ExpandBuff(bool wrapAround) {
char[] newbuffer = new char[(this.bufsize + 2048)];
int[] newbufline = new int[(this.bufsize + 2048)];
int[] newbufcolumn = new int[(this.bufsize + 2048)];
try {
if (wrapAround) {
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.buffer, this.tokenBegin, newbuffer, 0, (this.bufsize - this.tokenBegin));
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.buffer, 0, newbuffer, (this.bufsize - this.tokenBegin), this.bufpos);
this.buffer = newbuffer;
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.bufline, this.tokenBegin, newbufline, 0, (this.bufsize - this.tokenBegin));
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.bufline, 0, newbufline, (this.bufsize - this.tokenBegin), this.bufpos);
this.bufline = newbufline;
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.bufcolumn, this.tokenBegin, newbufcolumn, 0, (this.bufsize - this.tokenBegin));
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.bufcolumn, 0, newbufcolumn, (this.bufsize - this.tokenBegin), this.bufpos);
this.bufcolumn = newbufcolumn;
this.maxNextCharInd = (this.bufpos += (this.bufsize - this.tokenBegin));
} else {
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.buffer, this.tokenBegin, newbuffer, 0, (this.bufsize - this.tokenBegin));
this.buffer = newbuffer;
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.bufline, this.tokenBegin, newbufline, 0, (this.bufsize - this.tokenBegin));
this.bufline = newbufline;
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.bufcolumn, this.tokenBegin, newbufcolumn, 0, (this.bufsize - this.tokenBegin));
this.bufcolumn = newbufcolumn;
this.maxNextCharInd = (this.bufpos -= this.tokenBegin);
}
} catch (global::System.Exception t) {
throw new global::System.IO.IOException("Errow expanding the buffer.", t);
}
this.bufsize += 2048;
this.available = this.bufsize;
this.tokenBegin = 0;
}

protected internal virtual void FillBuff() {
if ((!(this.isStringProvider) && (this.maxNextCharInd == this.available))) {
if ((this.available == this.bufsize)) {
if ((this.tokenBegin > 2048)) {
this.bufpos = (this.maxNextCharInd = 0);
this.available = this.tokenBegin;
} else {
if ((this.tokenBegin < 0)) {
this.bufpos = (this.maxNextCharInd = 0);
} else {
this.ExpandBuff(false);
}
}
} else {
if ((this.available > this.tokenBegin)) {
this.available = this.bufsize;
} else {
if (((this.tokenBegin - this.available) < 2048)) {
this.ExpandBuff(true);
} else {
this.available = this.tokenBegin;
}
}
}
}
int i;
try {
if ((this.inputStream is global::DripSharp.SqlTrellis.Parser.StringProvider)) {
i = ((global::DripSharp.SqlTrellis.Parser.StringProvider)(this.inputStream!))._string.Length;
if ((this.maxNextCharInd == i)) {
throw new global::System.IO.IOException();
}
this.maxNextCharInd = i;
} else {
if (((i = this.inputStream.read(this.buffer, this.maxNextCharInd, (this.available - this.maxNextCharInd))) == -1)) {
this.inputStream.Dispose();
throw new global::System.IO.IOException();
} else {
this.maxNextCharInd += i;
}
}
return;
} catch (global::System.IO.IOException e) {
--(this.bufpos);
this.backup(0);
if ((this.tokenBegin == -1)) {
this.tokenBegin = this.bufpos;
}
global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(e);
throw new global::System.InvalidOperationException("unreachable");
}
}

public virtual char BeginToken() {
this.tokenBegin = -1;
char c = this.readChar();
this.tokenBegin = this.bufpos;
this.absoluteTokenBegin = this.totalCharsRead;
return c;
}

protected internal virtual void UpdateLineColumn(char c) {
this.column++;
if (this.prevCharIsLF) {
this.prevCharIsLF = false;
this.line += (this.column = 1);
} else {
if (this.prevCharIsCR) {
this.prevCharIsCR = false;
if (((int)(c) == (int)('\n'))) {
this.prevCharIsLF = true;
} else {
this.line += (this.column = 1);
}
}
}
switch (c) {
case var __case_225_18_0 when __case_225_18_0 == '\r':
this.prevCharIsCR = true;
break;
case var __case_228_18_0 when __case_228_18_0 == '\n':
this.prevCharIsLF = true;
break;
case var __case_231_18_0 when __case_231_18_0 == '\t':
this.column--;
this.column += (this.tabSize - (this.column % this.tabSize));
break;
default:
break;
}
this.bufline[this.bufpos] = this.line;
this.bufcolumn[this.bufpos] = this.column;
}

private char readChar(int pos) {
if ((this.inputStream is global::DripSharp.SqlTrellis.Parser.StringProvider)) {
return ((global::DripSharp.SqlTrellis.Parser.StringProvider)(this.inputStream!))._string[pos];
} else {
return this.buffer[pos];
}
}

public virtual char readChar() {
if ((this.inBuf > 0)) {
--(this.inBuf);
if ((++(this.bufpos) == this.bufsize)) {
this.bufpos = 0;
}
this.totalCharsRead++;
return this.readChar(this.bufpos);
}
if ((++(this.bufpos) >= this.maxNextCharInd)) {
this.FillBuff();
}
this.totalCharsRead++;
char c = this.readChar(this.bufpos);
this.UpdateLineColumn(c);
return c;
}

public virtual int getColumn() {
return this.bufcolumn[this.bufpos];
}

public virtual int getLine() {
return this.bufline[this.bufpos];
}

public virtual int getEndColumn() {
return this.bufcolumn[this.bufpos];
}

public virtual int getEndLine() {
return this.bufline[this.bufpos];
}

public virtual int getBeginColumn() {
return this.bufcolumn[this.tokenBegin];
}

public virtual int getBeginLine() {
return this.bufline[this.tokenBegin];
}

public virtual void backup(int amount) {
this.inBuf += amount;
this.totalCharsRead -= amount;
if (((this.bufpos -= amount) < 0)) {
this.bufpos += this.bufsize;
}
}

public virtual void ReInit(global::DripSharp.SqlTrellis.Parser.Provider dstream, int startline, int startcolumn, int buffersize) {
this.inputStream = dstream;
this.isStringProvider = (dstream is global::DripSharp.SqlTrellis.Parser.StringProvider);
this.line = startline;
this.column = (startcolumn - 1);
if (this.isStringProvider) {
int bs = ((global::DripSharp.SqlTrellis.Parser.StringProvider)(this.inputStream!))._string.Length;
this.available = (this.bufsize = bs);
this.bufline = new int[bs];
this.bufcolumn = new int[bs];
} else {
if (((this.buffer == default!) || (buffersize != this.buffer.Length))) {
this.available = (this.bufsize = buffersize);
this.buffer = new char[buffersize];
this.bufline = new int[buffersize];
this.bufcolumn = new int[buffersize];
}
}
this.prevCharIsLF = (this.prevCharIsCR = false);
this.tokenBegin = (this.inBuf = (this.maxNextCharInd = 0));
this.bufpos = -1;
}

public virtual void ReInit(global::DripSharp.SqlTrellis.Parser.Provider dstream, int startline, int startcolumn) {
this.ReInit(dstream, startline, startcolumn, 4096);
}

public virtual void ReInit(global::DripSharp.SqlTrellis.Parser.Provider dstream) {
this.ReInit(dstream, 1, 1, 4096);
}

public virtual string GetImage() {
if (this.isStringProvider) {
string data = ((global::DripSharp.SqlTrellis.Parser.StringProvider)(this.inputStream!))._string;
if ((this.bufpos >= this.tokenBegin)) {
return global::DripSharp.Runtime.JavaCompat.StringSubstring(data, this.tokenBegin, (this.bufpos + 1));
} else {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.StringSubstring(data, this.tokenBegin, this.bufsize), global::DripSharp.Runtime.JavaCompat.StringSubstring(data, 0, (this.bufpos + 1)));
}
} else {
if ((this.bufpos >= this.tokenBegin)) {
return new string(this.buffer, this.tokenBegin, ((this.bufpos - this.tokenBegin) + 1));
} else {
return global::DripSharp.Runtime.JavaCompat.Concat(new string(this.buffer, this.tokenBegin, (this.bufsize - this.tokenBegin)), new string(this.buffer, 0, (this.bufpos + 1)));
}
}
}

public virtual char[] GetSuffix(int len) {
char[] ret = new char[len];
if (this.isStringProvider) {
string str = ((global::DripSharp.SqlTrellis.Parser.StringProvider)(this.inputStream!))._string;
if (((this.bufpos + 1) >= len)) {
str.CopyTo(((this.bufpos - len) + 1), ret, 0, ((((this.bufpos - len) + 1) + len)) - (((this.bufpos - len) + 1)));
} else {
str.CopyTo((this.bufsize - ((len - this.bufpos) - 1)), ret, 0, (((((this.bufsize - ((len - this.bufpos) - 1)) + len) - this.bufpos) - 1)) - ((this.bufsize - ((len - this.bufpos) - 1))));
str.CopyTo(0, ret, ((len - this.bufpos) - 1), ((this.bufpos + 1)) - 0);
}
} else {
if (((this.bufpos + 1) >= len)) {
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.buffer, ((this.bufpos - len) + 1), ret, 0, len);
} else {
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.buffer, (this.bufsize - ((len - this.bufpos) - 1)), ret, 0, ((len - this.bufpos) - 1));
global::DripSharp.Runtime.JavaCompat.ArrayCopy(this.buffer, 0, ret, ((len - this.bufpos) - 1), (this.bufpos + 1));
}
}
return ret;
}

public virtual void Done() {
this.buffer = default!;
this.bufline = default!;
this.bufcolumn = default!;
}

public virtual void adjustBeginLineColumn(int newLine, int newCol) {
int nl = newLine;
int start = this.tokenBegin;
int len;
if ((this.bufpos >= this.tokenBegin)) {
len = (((this.bufpos - this.tokenBegin) + this.inBuf) + 1);
} else {
len = ((((this.bufsize - this.tokenBegin) + this.bufpos) + 1) + this.inBuf);
}
int i = 0;
int j = 0;
int k = 0;
int nextColDiff = 0;
int columnDiff = 0;
while (((i < len) && (this.bufline[(j = (start % this.bufsize))] == this.bufline[(k = (++start % this.bufsize))]))) {
this.bufline[j] = nl;
nextColDiff = ((columnDiff + this.bufcolumn[k]) - this.bufcolumn[j]);
this.bufcolumn[j] = (newCol + columnDiff);
columnDiff = nextColDiff;
i++;
}
if ((i < len)) {
this.bufline[j] = nl++;
this.bufcolumn[j] = (newCol + columnDiff);
while ((i++ < len)) {
if ((this.bufline[(j = (start % this.bufsize))] != this.bufline[(++start % this.bufsize)])) {
this.bufline[j] = nl++;
} else {
this.bufline[j] = nl;
}
}
}
this.line = this.bufline[j];
this.column = this.bufcolumn[j];
}

internal virtual bool getTrackLineColumn() {
return this.trackLineColumn;
}

internal virtual void setTrackLineColumn(bool tlc) {
this.trackLineColumn = tlc;
}
}
