// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/parser/StringProvider.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Parser;

public class StringProvider : global::DripSharp.SqlTrellis.Parser.Provider {
internal string _string = null!;

internal int _position = 0;

internal int _size = default;

public StringProvider(string @string) {
this._string = @string;
this._size = @string.Length;
}

public virtual int read(char[] cbuf, int off, int len) {
int numCharsOutstandingInString = (this._size - this._position);
if ((numCharsOutstandingInString == 0)) {
return -1;
}
int numBytesInBuffer = cbuf.Length;
int numBytesToRead = (numBytesInBuffer - off);
numBytesToRead = ((numBytesToRead > len) ? len : numBytesToRead);
if ((numBytesToRead > numCharsOutstandingInString)) {
numBytesToRead = numCharsOutstandingInString;
}
this._string.CopyTo(this._position, cbuf, off, ((this._position + numBytesToRead)) - (this._position));
this._position += numBytesToRead;
return numBytesToRead;
}

public virtual void Dispose() {
this._string = default!;
}
}
