// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/FromItemVisitorAdapter.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class FromItemVisitorAdapter<T> : global::DripSharp.SqlTrellis.Statement.Select.FromItemVisitor<T> {
public virtual T visit<S>(global::DripSharp.SqlTrellis.Schema.Table table, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect select, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.LateralSubSelect lateralSubSelect, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.TableFunction tableFunction, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedFromItem fromItem, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.Values values, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList setOperationList, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Piped.FromQuery fromQuery, S context) {
return default!;
}
}
