// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/PivotVisitorAdapter.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class PivotVisitorAdapter<T> : global::DripSharp.SqlTrellis.Statement.Select.PivotVisitor<T> {
public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.Pivot pivot, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.PivotXml pivot, S context) {
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.UnPivot unpivot, S context) {
return default!;
}
}
