// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/PivotXml.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class PivotXml : global::DripSharp.SqlTrellis.Statement.Select.Pivot {
private global::DripSharp.SqlTrellis.Statement.Select.Select inSelect = null!;

private bool inAny = false;

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.PivotVisitor<T> pivotVisitor, S context) {
return pivotVisitor.visit(this, context);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select getInSelect() {
return this.inSelect;
}

public virtual void setInSelect(global::DripSharp.SqlTrellis.Statement.Select.Select inSelect) {
this.inSelect = inSelect;
}

public virtual bool isInAny() {
return this.inAny;
}

public virtual void setInAny(bool inAny) {
this.inAny = inAny;
}

public override string ToString() {
global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Schema.Column> forColumns = this.getForColumns();
string @in = (this.inAny ? "ANY" : ((this.inSelect == default!) ? global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(this.getInItems())) : this.inSelect.ToString()));
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("PIVOT XML (", global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(this.getFunctionItems()))), " FOR "), global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(forColumns), true, ((forColumns != default!) && (global::DripSharp.Runtime.JavaCompat.CollectionCount(forColumns) > 1)))), " IN ("), @in), "))");
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.PivotXml withInSelect(global::DripSharp.SqlTrellis.Statement.Select.Select inSelect) {
this.setInSelect(inSelect);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.PivotXml withInAny(bool inAny) {
this.setInAny(inAny);
return this;
}

public virtual E getInSelect<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Statement.Select.Select {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getInSelect());
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot withAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.withAlias(alias)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot withFunctionItems(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Function>> functionItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.withFunctionItems(functionItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot withForColumns(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> forColumns) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.withForColumns(forColumns)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot withSingleInItems(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> singleInItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.withSingleInItems(singleInItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot withMultiInItems(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>>> multiInItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.withMultiInItems(multiInItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addFunctionItems(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Function>> functionItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addFunctionItems(functionItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addFunctionItems(params global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Function>[] functionItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addFunctionItems(functionItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addForColumns(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> forColumns) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addForColumns(forColumns)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addForColumns(params global::DripSharp.SqlTrellis.Schema.Column[] forColumns) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addForColumns(forColumns)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addSingleInItems(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> singleInItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addSingleInItems(singleInItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addSingleInItems(params global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>[] singleInItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addSingleInItems(singleInItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addMultiInItems(params global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>>[] multiInItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addMultiInItems(multiInItems)!);
}

public override global::DripSharp.SqlTrellis.Statement.Select.Pivot addMultiInItems(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>>> multiInItems) {
return (global::DripSharp.SqlTrellis.Statement.Select.PivotXml)(base.addMultiInItems(multiInItems)!);
}
}
