// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/Select.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public abstract class Select : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression, global::DripSharp.SqlTrellis.Statement.Statement, global::DripSharp.SqlTrellis.Statement.Select.FromItem {
protected internal global::DripSharp.SqlTrellis.Schema.Table forUpdateTable = default!;

protected internal global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> withItemsList = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.Limit limitBy = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.Limit limit = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.Offset offset = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.Fetch fetch = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.WithIsolation isolation = null!;

internal bool oracleSiblings = false;

internal global::DripSharp.SqlTrellis.Statement.Select.ForClause forClause = default!;

internal global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.ForMode forMode = default!;

private bool skipLocked = default;

private global::DripSharp.SqlTrellis.Statement.Select.Wait wait = null!;

private bool noWait = false;

internal global::DripSharp.SqlTrellis.Expression.Alias alias = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.Pivot pivot = null!;

internal global::DripSharp.SqlTrellis.Statement.Select.UnPivot unPivot = null!;

public static string orderByToString(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
return global::DripSharp.SqlTrellis.Statement.Select.Select.orderByToString(false, orderByElements);
}

public static string orderByToString(bool oracleSiblings, global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
return global::DripSharp.SqlTrellis.Statement.Select.Select.getFormattedList(global::DripSharp.Runtime.JavaCompat.CastObjects(orderByElements), (oracleSiblings ? "ORDER SIBLINGS BY" : "ORDER BY"));
}

public static string getFormattedList(global::System.Collections.Generic.IEnumerable<object> list, string expression) {
return global::DripSharp.SqlTrellis.Statement.Select.Select.getFormattedList(global::DripSharp.Runtime.JavaCompat.CastObjects(list), expression, true, false);
}

public static string getFormattedList(global::System.Collections.Generic.IEnumerable<object> list, string expression, bool useComma, bool useBrackets) {
string sql = global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(list), useComma, useBrackets);
if (!((sql.Length == 0))) {
if (!((expression.Length == 0))) {
sql = global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(" ", expression), " "), sql);
} else {
sql = global::DripSharp.Runtime.JavaCompat.Concat(" ", sql);
}
}
return sql;
}

public static string getStringList(global::System.Collections.Generic.IEnumerable<object> list) {
return global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(list), true, false);
}

public static string getStringList(global::System.Collections.Generic.IEnumerable<object> list, bool useComma, bool useBrackets) {
return global::DripSharp.SqlTrellis.Statement.Select.Select.appendStringListTo(new global::System.Text.StringBuilder(), global::DripSharp.Runtime.JavaCompat.CastObjects(list), useComma, useBrackets).ToString();
}

public static global::System.Text.StringBuilder appendStringListTo(global::System.Text.StringBuilder builder, global::System.Collections.Generic.IEnumerable<object> list, bool useComma, bool useBrackets) {
if ((list != default!)) {
string comma = (useComma ? ", " : " ");
if (useBrackets) {
builder.Append("(");
}
int size = global::DripSharp.Runtime.JavaCompat.CollectionCount(list);
for (int i = 0; (i < size); i++) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(global::DripSharp.Runtime.JavaCompat.ListGet(list, i))).Append(((i < (size - 1)) ? comma : ""));
}
if (useBrackets) {
builder.Append(")");
}
}
return builder;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> getWithItemsList() {
return this.withItemsList;
}

public virtual void setWithItemsList(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> withItemsList) {
this.withItemsList = withItemsList;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withWithItemsList(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> withItemsList) {
this.setWithItemsList(withItemsList);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select addWithItemsList(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> withItemsList) {
global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> collection = global::DripSharp.Runtime.JavaOptional<global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>>>.OfNullable(this.getWithItemsList()).OrElseGet(() => new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>>());
global::DripSharp.Runtime.JavaCompat.AddAll(collection, withItemsList);
return this.withWithItemsList(collection);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select addWithItemsList(params global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>[] withItemsList) {
return this.addWithItemsList(global::DripSharp.Runtime.JavaCompat.AsList<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>>(withItemsList));
}

public virtual bool isOracleSiblings() {
return this.oracleSiblings;
}

public virtual void setOracleSiblings(bool oracleSiblings) {
this.oracleSiblings = oracleSiblings;
}

public virtual bool isNoWait() {
return this.noWait;
}

public virtual void setNoWait(bool noWait) {
this.noWait = noWait;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withOracleSiblings(bool oracleSiblings) {
this.setOracleSiblings(oracleSiblings);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.ForClause getForClause() {
return this.forClause;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select setForClause(global::DripSharp.SqlTrellis.Statement.Select.ForClause forClause) {
this.forClause = forClause;
return this;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> getOrderByElements() {
return this.orderByElements;
}

public virtual void setOrderByElements(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
this.orderByElements = orderByElements;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withOrderByElements(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
this.setOrderByElements(orderByElements);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select addOrderByElements(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> collection = global::DripSharp.Runtime.JavaOptional<global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement>>.OfNullable(this.getOrderByElements()).OrElseGet(() => new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement>());
global::DripSharp.Runtime.JavaCompat.AddAll(collection, orderByElements);
return this.withOrderByElements(collection);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select addOrderByElements(params global::DripSharp.SqlTrellis.Statement.Select.OrderByElement[] orderByElements) {
return this.addOrderByElements(global::DripSharp.Runtime.JavaCompat.AsList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement>(orderByElements));
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select addOrderByExpressions(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Expression.Expression> orderByExpressions) {
foreach (global::DripSharp.SqlTrellis.Expression.Expression e in orderByExpressions) {
this.addOrderByElements(new global::DripSharp.SqlTrellis.Statement.Select.OrderByElement().withExpression(e));
}
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select addOrderByElements(params global::DripSharp.SqlTrellis.Expression.Expression[] orderByExpressions) {
return this.addOrderByExpressions(global::DripSharp.Runtime.JavaCompat.AsList<global::DripSharp.SqlTrellis.Expression.Expression>(orderByExpressions));
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Limit getLimit() {
return this.limit;
}

public virtual void setLimit(global::DripSharp.SqlTrellis.Statement.Select.Limit limit) {
this.limit = limit;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withLimit(global::DripSharp.SqlTrellis.Statement.Select.Limit limit) {
this.setLimit(limit);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Limit getLimitBy() {
return this.limitBy;
}

public virtual void setLimitBy(global::DripSharp.SqlTrellis.Statement.Select.Limit limitBy) {
this.limitBy = limitBy;
}

public virtual E withLimitBy<E>(global::System.Type type, global::DripSharp.SqlTrellis.Statement.Select.Limit limitBy) where E : global::DripSharp.SqlTrellis.Statement.Select.Select {
this.setLimitBy(limitBy);
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Offset getOffset() {
return this.offset;
}

public virtual void setOffset(global::DripSharp.SqlTrellis.Statement.Select.Offset offset) {
this.offset = offset;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withOffset(global::DripSharp.SqlTrellis.Statement.Select.Offset offset) {
this.setOffset(offset);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Fetch getFetch() {
return this.fetch;
}

public virtual void setFetch(global::DripSharp.SqlTrellis.Statement.Select.Fetch fetch) {
this.fetch = fetch;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withFetch(global::DripSharp.SqlTrellis.Statement.Select.Fetch fetch) {
this.setFetch(fetch);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.WithIsolation getIsolation() {
return this.isolation;
}

public virtual void setIsolation(global::DripSharp.SqlTrellis.Statement.Select.WithIsolation isolation) {
this.isolation = isolation;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withIsolation(global::DripSharp.SqlTrellis.Statement.Select.WithIsolation isolation) {
this.setIsolation(isolation);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.ForMode getForMode() {
return this.forMode;
}

public virtual void setForMode(global::DripSharp.SqlTrellis.Statement.Select.ForMode forMode) {
this.forMode = forMode;
}

public virtual global::DripSharp.SqlTrellis.Schema.Table getForUpdateTable() {
return this.forUpdateTable;
}

public virtual void setForUpdateTable(global::DripSharp.SqlTrellis.Schema.Table forUpdateTable) {
this.forUpdateTable = forUpdateTable;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Wait getWait() {
return this.wait;
}

public virtual void setWait(global::DripSharp.SqlTrellis.Statement.Select.Wait wait) {
this.wait = wait;
}

public virtual bool isSkipLocked() {
return this.skipLocked;
}

public virtual void setSkipLocked(bool skipLocked) {
this.skipLocked = skipLocked;
}

public virtual global::DripSharp.SqlTrellis.Expression.Alias getAlias() {
return this.alias;
}

public virtual void setAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.alias = alias;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.setAlias(alias);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Pivot getPivot() {
return this.pivot;
}

public virtual void setPivot(global::DripSharp.SqlTrellis.Statement.Select.Pivot pivot) {
this.pivot = pivot;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.UnPivot getUnPivot() {
return this.unPivot;
}

public virtual void setUnPivot(global::DripSharp.SqlTrellis.Statement.Select.UnPivot unPivot) {
this.unPivot = unPivot;
}

public virtual global::System.Text.StringBuilder appendSelectBodyTo(global::System.Text.StringBuilder builder) {
return builder;
}

public override global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
if (((this.withItemsList != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.withItemsList)))) {
builder.Append("WITH ");
for (global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> iter = global::DripSharp.Runtime.JavaCompat.Iterator(this.withItemsList); iter.HasNext(); ) {
global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement> withItem = iter.Next()!;
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(withItem));
if (iter.HasNext()) {
builder.Append(",");
}
builder.Append(" ");
}
}
this.appendSelectBodyTo(builder);
((global::DripSharp.SqlTrellis.Statement.Select.FromItem)(this)).appendTo(builder, this.alias, (global::DripSharp.SqlTrellis.Statement.Select.SampleClause)default!, this.pivot, this.unPivot);
if ((this.forClause != default!)) {
this.forClause.appendTo(builder);
}
builder.Append(global::DripSharp.SqlTrellis.Statement.Select.Select.orderByToString(this.oracleSiblings, this.orderByElements));
if ((this.limitBy != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.limitBy));
}
if ((this.limit != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.limit));
}
if ((this.offset != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.offset));
}
if ((this.fetch != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.fetch));
}
if ((this.isolation != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.isolation));
}
if ((this.forMode != default!)) {
builder.Append(" FOR ");
builder.Append(this.forMode.getValue());
if ((this.getForUpdateTable() != default!)) {
builder.Append(" OF ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.forUpdateTable));
}
if ((this.wait != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.wait));
}
if (this.isNoWait()) {
builder.Append(" NOWAIT");
} else {
if (this.isSkipLocked()) {
builder.Append(" SKIP LOCKED");
}
}
}
return builder;
}

public override string ToString() {
return this.appendTo(new global::System.Text.StringBuilder()).ToString();
}

public abstract T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T> selectVisitor, S context);

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<T> statementVisitor, S context) {
return statementVisitor.visit(this, context);
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select getSelectBody() {
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Values getValues() {
return (global::DripSharp.SqlTrellis.Statement.Select.Values)(this!);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.PlainSelect getPlainSelect() {
return (global::DripSharp.SqlTrellis.Statement.Select.PlainSelect)(this!);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.SetOperationList getSetOperationList() {
return (global::DripSharp.SqlTrellis.Statement.Select.SetOperationList)(this!);
}

public virtual E @as<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Statement.Select.Select {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this);
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withForMode(global::DripSharp.SqlTrellis.Statement.Select.ForMode forMode) {
this.setForMode(forMode);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withForUpdateTable(global::DripSharp.SqlTrellis.Schema.Table forUpdateTable) {
this.setForUpdateTable(forUpdateTable);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withSkipLocked(bool skipLocked) {
this.setSkipLocked(skipLocked);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select withWait(global::DripSharp.SqlTrellis.Statement.Select.Wait wait) {
this.setWait(wait);
return this;
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}

public virtual void accept<TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<TWildcard0_0> statementVisitor) {
this.accept<TWildcard0_0, object>(statementVisitor, (object)default!);
}

public virtual void accept<TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.FromItemVisitor<TWildcard0_0> fromItemVisitor) {
this.accept<TWildcard0_0, object>(fromItemVisitor, (object)default!);
}

public abstract T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.FromItemVisitor<T> fromItemVisitor, S context);

public virtual global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder, global::DripSharp.SqlTrellis.Expression.Alias alias) {
return ((global::DripSharp.SqlTrellis.Statement.Select.FromItem)(this)).appendTo(builder, alias, (global::DripSharp.SqlTrellis.Statement.Select.SampleClause)default!, (global::DripSharp.SqlTrellis.Statement.Select.Pivot)default!, (global::DripSharp.SqlTrellis.Statement.Select.UnPivot)default!);
}

public virtual global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder, global::DripSharp.SqlTrellis.Expression.Alias alias, global::DripSharp.SqlTrellis.Statement.Select.SampleClause sampleClause, global::DripSharp.SqlTrellis.Statement.Select.Pivot pivot, global::DripSharp.SqlTrellis.Statement.Select.UnPivot unPivot) {
if ((alias != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(alias));
}
if ((sampleClause != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(sampleClause));
}
if ((pivot != default!)) {
builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(pivot));
}
if ((unPivot != default!)) {
builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(unPivot));
}
return builder;
}

public abstract global::DripSharp.SqlTrellis.Statement.Select.SampleClause getSampleClause();

public abstract global::DripSharp.SqlTrellis.Statement.Select.FromItem setSampleClause(global::DripSharp.SqlTrellis.Statement.Select.SampleClause sampleClause);

global::DripSharp.SqlTrellis.Statement.Select.FromItem global::DripSharp.SqlTrellis.Statement.Select.FromItem.withAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) => (global::DripSharp.SqlTrellis.Statement.Select.FromItem)(this.withAlias(alias));

public virtual global::DripSharp.SqlTrellis.Statement.Select.FromItem withPivot(global::DripSharp.SqlTrellis.Statement.Select.Pivot pivot) {
this.setPivot(pivot);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.FromItem withUnPivot(global::DripSharp.SqlTrellis.Statement.Select.UnPivot unpivot) {
this.setUnPivot(unpivot);
return this;
}

public Select() {}
}
