// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/SelectItem.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class SelectItem<T> : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl where T : global::DripSharp.SqlTrellis.Expression.Expression {
private T expression = default!;

private global::DripSharp.SqlTrellis.Expression.Alias alias = null!;

public SelectItem(T expression, global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.expression = expression;
this.alias = alias;
}

public SelectItem(T expression, string aliasName) {
this.expression = expression;
this.alias = new global::DripSharp.SqlTrellis.Expression.Alias(aliasName);
}

public SelectItem(long? expression, string aliasName) : this(global::DripSharp.Runtime.JavaCompat.CastReference<T>(new global::DripSharp.SqlTrellis.Expression.LongValue((long)(global::DripSharp.Runtime.JavaCompat.Unbox(expression)))), aliasName) {

}

public SelectItem(int? expression, string aliasName) : this(global::DripSharp.Runtime.JavaCompat.CastReference<T>(new global::DripSharp.SqlTrellis.Expression.LongValue((long)(global::DripSharp.Runtime.JavaCompat.Unbox(expression)))), aliasName) {

}

public SelectItem(double? expression, string aliasName) : this(global::DripSharp.Runtime.JavaCompat.CastReference<T>(new global::DripSharp.SqlTrellis.Expression.DoubleValue((double)(global::DripSharp.Runtime.JavaCompat.Unbox(expression)))), aliasName) {

}

public SelectItem(string expression, string aliasName) : this(global::DripSharp.Runtime.JavaCompat.CastReference<T>(new global::DripSharp.SqlTrellis.Expression.StringValue(expression)), aliasName) {

}

public SelectItem() : this((T)default!, (global::DripSharp.SqlTrellis.Expression.Alias)default!) {

}

public SelectItem(T expression) : this(expression, (global::DripSharp.SqlTrellis.Expression.Alias)default!) {

}

public static global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression> from(global::DripSharp.SqlTrellis.Expression.Expression expression, global::DripSharp.SqlTrellis.Expression.Alias alias) {
return new global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>(expression, alias);
}

public static global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression> from(global::DripSharp.SqlTrellis.Expression.Expression expression) {
return global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>.from(expression, (global::DripSharp.SqlTrellis.Expression.Alias)default!);
}

public virtual global::DripSharp.SqlTrellis.Expression.Alias getAlias() {
return this.alias;
}

public virtual string getAliasName() {
return ((this.alias != default!) ? this.alias.getName() : (string)(default!));
}

public virtual string getUnquotedAliasName() {
return ((this.alias != default!) ? this.alias.getUnquotedName() : (string)(default!));
}

public virtual void setAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.alias = alias;
}

public virtual T getExpression() {
return this.expression;
}

public virtual void setExpression(T expression) {
this.expression = expression;
}

public virtual K accept<K, S>(global::DripSharp.SqlTrellis.Statement.Select.SelectItemVisitor<K> selectItemVisitor, S context) {
return selectItemVisitor.visit<S, T>(this, context);
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(this.expression, ((this.alias != default!) ? this.alias.ToString() : ""));
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.SelectItem<T> withExpression(T expression) {
this.setExpression(expression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.SelectItem<T> withAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.setAlias(alias);
return this;
}

public virtual E getExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getExpression());
}
}
