// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/SelectVisitor.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public interface SelectVisitor<out T> {
public T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect parenthesedSelect, S context);

public void visit(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect parenthesedSelect);

public T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect, S context);

public void visit(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect);

public T visit<S>(global::DripSharp.SqlTrellis.Statement.Piped.FromQuery fromQuery, S context);

public T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList setOpList, S context);

public void visit(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList setOpList);

public T visit<S, TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.WithItem<TWildcard0_0> withItem, S context) where TWildcard0_0 : global::DripSharp.SqlTrellis.Statement.ParenthesedStatement;

public void visit<TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.WithItem<TWildcard0_0> withItem) where TWildcard0_0 : global::DripSharp.SqlTrellis.Statement.ParenthesedStatement;

public T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.Values values, S context);

public void visit(global::DripSharp.SqlTrellis.Statement.Select.Values values);

public T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.LateralSubSelect lateralSubSelect, S context);

public void visit(global::DripSharp.SqlTrellis.Statement.Select.LateralSubSelect lateralSubSelect);

public T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement, S context);

public void visit(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement);
}
