// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/SetOperation.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public abstract class SetOperation : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl {
private global::DripSharp.SqlTrellis.Statement.Select.SetOperationList.SetOperationType type = null!;

public SetOperation(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList.SetOperationType type) {
this.type = type;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.EnumName(this.type);
}
}
