// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/Skip.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class Skip {
private long? rowCount = default;

private global::DripSharp.SqlTrellis.Expression.JdbcParameter jdbcParameter = null!;

private string variable = null!;

public virtual long? getRowCount() {
return this.rowCount;
}

public virtual void setRowCount(long? rowCount) {
this.rowCount = rowCount;
}

public virtual global::DripSharp.SqlTrellis.Expression.JdbcParameter getJdbcParameter() {
return this.jdbcParameter;
}

public virtual void setJdbcParameter(global::DripSharp.SqlTrellis.Expression.JdbcParameter jdbcParameter) {
this.jdbcParameter = jdbcParameter;
}

public virtual string getVariable() {
return this.variable;
}

public virtual void setVariable(string variable) {
this.variable = variable;
}

public override string ToString() {
string result = "SKIP ";
if ((this.rowCount != default!)) {
result += this.rowCount;
} else {
if ((this.jdbcParameter != default!)) {
result += this.jdbcParameter.ToString();
} else {
if ((this.variable != default!)) {
result += this.variable;
}
}
}
return result;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Skip withRowCount(long? rowCount) {
this.setRowCount(rowCount);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Skip withJdbcParameter(global::DripSharp.SqlTrellis.Expression.JdbcParameter jdbcParameter) {
this.setJdbcParameter(jdbcParameter);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Skip withVariable(string variable) {
this.setVariable(variable);
return this;
}
}
