// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/TableStatement.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class TableStatement : global::DripSharp.SqlTrellis.Statement.Select.Select {
private global::DripSharp.SqlTrellis.Schema.Table table = null!;

public virtual global::DripSharp.SqlTrellis.Schema.Table getTable() {
return this.table;
}

public virtual void setTable(global::DripSharp.SqlTrellis.Schema.Table table) {
this.table = table;
}

public override global::System.Text.StringBuilder appendSelectBodyTo(global::System.Text.StringBuilder builder) {
builder.Append("TABLE ").Append(this.table.getName());
return builder;
}

public override global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
this.appendSelectBodyTo(builder);
builder.Append(global::DripSharp.SqlTrellis.Statement.Select.Select.orderByToString(false, base.orderByElements));
if ((base.limit != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(base.limit));
}
if ((base.offset != default!)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(base.offset));
}
return builder;
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T> selectVisitor, S context) {
return selectVisitor.visit(this, context);
}

public override T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.FromItemVisitor<T> fromItemVisitor, S context) {
return fromItemVisitor.visit(this, context);
}

public override global::DripSharp.SqlTrellis.Statement.Select.SampleClause getSampleClause() {
return default!;
}

public override global::DripSharp.SqlTrellis.Statement.Select.FromItem setSampleClause(global::DripSharp.SqlTrellis.Statement.Select.SampleClause sampleClause) {
return default!;
}
}
