// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/select/UnPivot.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Select;

public class UnPivot {
private bool includeNulls = false;

private bool includeNullsSpecified = false;

private global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> unpivotClause = null!;

private global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> unpivotForClause = null!;

private global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> unpivotInClause = null!;

private global::DripSharp.SqlTrellis.Expression.Alias alias = null!;

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.Select.PivotVisitor<T> pivotVisitor, S context) {
return pivotVisitor.visit(this, context);
}

public virtual bool getIncludeNulls() {
return this.includeNulls;
}

public virtual void setIncludeNulls(bool includeNulls) {
this.includeNullsSpecified = true;
this.includeNulls = includeNulls;
}

public virtual bool getIncludeNullsSpecified() {
return this.includeNullsSpecified;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Schema.Column> getUnPivotClause() {
return this.unpivotClause;
}

public virtual void setUnPivotClause(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> unpivotClause) {
this.unpivotClause = unpivotClause;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Schema.Column> getUnPivotForClause() {
return this.unpivotForClause;
}

public virtual void setUnPivotForClause(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> forColumns) {
this.unpivotForClause = forColumns;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> getUnPivotInClause() {
return this.unpivotInClause;
}

public virtual void setUnPivotInClause(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> unpivotInClause) {
this.unpivotInClause = unpivotInClause;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("UNPIVOT", ((this.includeNullsSpecified && this.includeNulls) ? " INCLUDE NULLS" : "")), ((this.includeNullsSpecified && !(this.includeNulls)) ? " EXCLUDE NULLS" : "")), " ("), this.unpivotClause.ToString()), " FOR "), this.unpivotForClause.ToString()), " IN "), global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(this.unpivotInClause), true, true)), ")"), ((this.alias != default!) ? this.alias.ToString() : ""));
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.UnPivot withIncludeNulls(bool includeNulls) {
this.setIncludeNulls(includeNulls);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Alias getAlias() {
return this.alias;
}

public virtual void setAlias(global::DripSharp.SqlTrellis.Expression.Alias alias) {
this.alias = alias;
}
}
