// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/execute/Execute.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Execute;

public class Execute : global::DripSharp.SqlTrellis.Statement.Statement {
private global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType execType = global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType.EXECUTE;

private string name = null!;

private global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> exprList = null!;

public virtual string getName() {
return this.name;
}

public virtual void setName(string name) {
this.name = name;
}

public virtual void setName(global::System.Collections.Generic.IList<string> names) {
foreach (string item in names) {
if ((this.name != default!)) {
this.name = global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.name, "."), item);
} else {
this.name = item;
}
}
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> getExprList() {
return this.exprList;
}

public virtual void setExprList(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> exprList) {
this.exprList = exprList;
}

public virtual global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType getExecType() {
return this.execType;
}

public virtual void setExecType(global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType execType) {
this.execType = execType;
}

public virtual bool isParenthesis() {
return (this.exprList is global::DripSharp.SqlTrellis.Expression.Operators.Relational.ParenthesedExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>);
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<T> statementVisitor, S context) {
return statementVisitor.visit(this, context);
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.EnumName(this.execType), " "), this.name), ((this.exprList != default!) ? global::DripSharp.Runtime.JavaCompat.Concat(" ", global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(this.exprList), true, (this.exprList is global::DripSharp.SqlTrellis.Expression.Operators.Relational.ParenthesedExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>))) : ""));
}

public virtual global::DripSharp.SqlTrellis.Statement.Execute.Execute withExecType(global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType execType) {
this.setExecType(execType);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Execute.Execute withName(string name) {
this.setName(name);
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Execute.Execute withExprList(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> exprList) {
this.setExprList(exprList);
return this;
}

public sealed class ExecType {
[global::DripSharp.Runtime.JavaEnumNameAttribute("EXECUTE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType EXECUTE = new global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("EXEC")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType EXEC = new global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("CALL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType CALL = new global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType();

public static global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType from(string type) {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Statement.Execute.Execute.ExecType>(type.ToUpper());
}

private ExecType() {}


public static ExecType[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<ExecType>();
public static ExecType valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<ExecType>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
}
