// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/insert/ConflictActionType.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Insert;

public sealed class ConflictActionType {
[global::DripSharp.Runtime.JavaEnumNameAttribute("DO_NOTHING")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.Insert.ConflictActionType DO_NOTHING = new global::DripSharp.SqlTrellis.Statement.Insert.ConflictActionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("DO_UPDATE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.Insert.ConflictActionType DO_UPDATE = new global::DripSharp.SqlTrellis.Statement.Insert.ConflictActionType();

public static global::DripSharp.SqlTrellis.Statement.Insert.ConflictActionType from(string type) {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Statement.Insert.ConflictActionType>(type.ToUpper());
}

private ConflictActionType() {}


public static ConflictActionType[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<ConflictActionType>();
public static ConflictActionType valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<ConflictActionType>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
