// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/create/view/ForceOption.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Create.View;

public sealed class ForceOption {
[global::DripSharp.Runtime.JavaEnumNameAttribute("NONE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption NONE = new global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FORCE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption FORCE = new global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption();

[global::DripSharp.Runtime.JavaEnumNameAttribute("NO_FORCE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption NO_FORCE = new global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption();

public static global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption from(string option) {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Statement.Create.View.ForceOption>(option.ToUpper());
}

private ForceOption() {}


public static ForceOption[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<ForceOption>();
public static ForceOption valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<ForceOption>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
