// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/create/view/TemporaryOption.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Create.View;

public sealed class TemporaryOption {
[global::DripSharp.Runtime.JavaEnumNameAttribute("NONE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption NONE = new global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TEMP")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption TEMP = new global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TEMPORARY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption TEMPORARY = new global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption();

[global::DripSharp.Runtime.JavaEnumNameAttribute("VOLATILE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption VOLATILE = new global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption();

public static global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption from(string option) {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Statement.Create.View.TemporaryOption>(option.ToUpper());
}

private TemporaryOption() {}


public static TemporaryOption[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<TemporaryOption>();
public static TemporaryOption valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<TemporaryOption>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
