// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/BinaryExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public abstract class BinaryExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private global::DripSharp.SqlTrellis.Expression.Expression leftExpression = null!;

private global::DripSharp.SqlTrellis.Expression.Expression rightExpression = null!;

public BinaryExpression() {}

public BinaryExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression, global::DripSharp.SqlTrellis.Expression.Expression rightExpression) {
this.leftExpression = leftExpression;
this.rightExpression = rightExpression;
}

public static global::DripSharp.SqlTrellis.Expression.Expression build(global::System.Type clz, params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
switch (expressions.Length) {
case var __case_53_18_0 when __case_53_18_0 == 0:
return new global::DripSharp.SqlTrellis.Expression.NullValue();
case var __case_55_18_0 when __case_55_18_0 == 1:
return expressions[0];
default:
global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Expression.Expression> it = global::DripSharp.Runtime.JavaCompat.Iterator(global::DripSharp.Runtime.JavaCompat.StreamOf<global::DripSharp.SqlTrellis.Expression.Expression>(expressions));
global::DripSharp.SqlTrellis.Expression.Expression leftExpression = it.Next()!;
global::DripSharp.SqlTrellis.Expression.Expression rightExpression = it.Next()!;
global::DripSharp.SqlTrellis.Expression.BinaryExpression binaryExpression = global::DripSharp.Runtime.JavaCompat.ConstructorInvoke<global::DripSharp.SqlTrellis.Expression.BinaryExpression>(global::DripSharp.Runtime.JavaCompat.ClassGetConstructor(clz, typeof(global::DripSharp.SqlTrellis.Expression.Expression), typeof(global::DripSharp.SqlTrellis.Expression.Expression)), leftExpression, rightExpression);
while (it.HasNext()) {
rightExpression = it.Next()!;
binaryExpression = global::DripSharp.Runtime.JavaCompat.ConstructorInvoke<global::DripSharp.SqlTrellis.Expression.BinaryExpression>(global::DripSharp.Runtime.JavaCompat.ClassGetConstructor(clz, typeof(global::DripSharp.SqlTrellis.Expression.Expression), typeof(global::DripSharp.SqlTrellis.Expression.Expression)), binaryExpression, rightExpression);
}
return binaryExpression;
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression add(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Addition), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression bitAnd(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseAnd), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression bitShiftLeft(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseLeftShift), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression multiply(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Multiplication), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression bitOr(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseOr), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression bitShiftRight(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseRightShift), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression bitXor(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseXor), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression concat(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Concat), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression divide(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Division), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression divideInt(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.IntegerDivision), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression modulo(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Modulo), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression subtract(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Subtraction), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression or(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.OrExpression), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression xor(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.XorExpression), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public static global::DripSharp.SqlTrellis.Expression.Expression and(params global::DripSharp.SqlTrellis.Expression.Expression[] expressions) {
try {
return global::DripSharp.SqlTrellis.Expression.BinaryExpression.build(typeof(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.AndExpression), expressions);
} catch (global::System.Exception e) when (e is global::System.MissingMethodException or global::System.Reflection.TargetInvocationException or global::System.MemberAccessException) {
throw new global::System.Exception(null, e);
}
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getLeftExpression() {
return this.leftExpression;
}

public virtual void setLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.leftExpression = expression;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getRightExpression() {
return this.rightExpression;
}

public virtual void setRightExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.rightExpression = expression;
}

public virtual global::DripSharp.SqlTrellis.Expression.BinaryExpression withLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.setLeftExpression(expression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.BinaryExpression withRightExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.setRightExpression(expression);
return this;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.getLeftExpression(), " "), this.getStringExpression()), " "), this.getRightExpression());
}

public abstract string getStringExpression();

public virtual E getLeftExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getLeftExpression());
}

public virtual E getRightExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getRightExpression());
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}

public abstract T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context);
}
