// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/CastExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class CastExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private static readonly global::System.Text.RegularExpressions.Regex PATTERN = global::DripSharp.Runtime.JavaCompat.CompileRegex("(^[a-z0-9_]*){1}", 2);

public string keyword = null!;

private global::DripSharp.SqlTrellis.Expression.Expression leftExpression = null!;

private global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType = default!;

private global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Create.Table.ColumnDefinition> columnDefinitions = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Create.Table.ColumnDefinition>();

private bool __field_isImplicitCast = false;

private string format = default!;

public CastExpression(string keyword, global::DripSharp.SqlTrellis.Expression.Expression leftExpression, string dataType) {
this.keyword = keyword;
this.leftExpression = leftExpression;
this.colDataType = new global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType(dataType);
}

public CastExpression(string dataType, string value) {
this.keyword = default!;
this.__field_isImplicitCast = true;
this.colDataType = new global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType(dataType);
this.leftExpression = new global::DripSharp.SqlTrellis.Expression.StringValue(value);
}

public CastExpression(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType, string value) {
this.keyword = default!;
this.__field_isImplicitCast = true;
this.colDataType = colDataType;
this.leftExpression = new global::DripSharp.SqlTrellis.Expression.StringValue(value);
}

public CastExpression(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType, long? value) {
this.keyword = default!;
this.__field_isImplicitCast = true;
this.colDataType = colDataType;
this.leftExpression = new global::DripSharp.SqlTrellis.Expression.LongValue((long)(global::DripSharp.Runtime.JavaCompat.Unbox(value)));
}

public CastExpression(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType, double? value) {
this.keyword = default!;
this.__field_isImplicitCast = true;
this.colDataType = colDataType;
this.leftExpression = new global::DripSharp.SqlTrellis.Expression.DoubleValue((double)(global::DripSharp.Runtime.JavaCompat.Unbox(value)));
}

public CastExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression, string dataType) {
this.keyword = default!;
this.leftExpression = leftExpression;
this.colDataType = new global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType(dataType);
}

public CastExpression(string keyword) {
this.keyword = keyword;
}

public CastExpression() : this("CAST") {

}

public static bool isOf(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType, params global::DripSharp.SqlTrellis.Expression.CastExpression.DataType[] types) {
return global::DripSharp.Runtime.JavaCompat.CollectionContains(global::DripSharp.Runtime.JavaCompat.EnumSetOf<global::DripSharp.SqlTrellis.Expression.CastExpression.DataType>(types), global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.from(colDataType.getDataType()));
}

public static bool isTime(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIME, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIME_WITH_TIME_ZONE, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIME_WITHOUT_TIME_ZONE);
}

public static bool isTimeStamp(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMP_NS, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMP, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMP_WITHOUT_TIME_ZONE, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.DATETIME, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMP_MS, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMP_S, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMPTZ, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TIMESTAMP_WITH_TIME_ZONE);
}

public static bool isDate(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.DATE);
}

public static bool isBLOB(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.BLOB, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.BYTEA, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.BINARY, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.VARBINARY, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.BYTES, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.VARBYTE);
}

public static bool isFloat(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.REAL, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.FLOAT4, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.FLOAT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.DOUBLE, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.DOUBLE_PRECISION, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.FLOAT8);
}

public static bool isInteger(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TINYINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.INT1, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.SMALLINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.INT2, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.SHORT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.INTEGER, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.INT4, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.INT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.SIGNED, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.BIGINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.INT8, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.LONG, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.HUGEINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.UTINYINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.USMALLINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.UINTEGER, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.UBIGINT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.UHUGEINT);
}

public static bool isDecimal(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.DECIMAL, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.NUMBER, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.NUMERIC);
}

public static bool isText(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isOf(colDataType, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.VARCHAR, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.NVARCHAR, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.CHAR, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.NCHAR, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.BPCHAR, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.STRING, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.TEXT, global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.CLOB);
}

public virtual global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType getColDataType() {
return this.colDataType;
}

public virtual void setColDataType(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType colDataType) {
this.colDataType = colDataType;
}

public virtual global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Create.Table.ColumnDefinition> getColumnDefinitions() {
return this.columnDefinitions;
}

public virtual void addColumnDefinition(global::DripSharp.SqlTrellis.Statement.Create.Table.ColumnDefinition columnDefinition) {
global::DripSharp.Runtime.JavaCompat.Add(this.columnDefinitions, columnDefinition);
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getLeftExpression() {
return this.leftExpression;
}

public virtual void setLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.leftExpression = expression;
}

public virtual bool isImplicitCast() {
return this.__field_isImplicitCast;
}

public virtual global::DripSharp.SqlTrellis.Expression.CastExpression setImplicitCast(bool implicitCast) {
this.__field_isImplicitCast = implicitCast;
return this;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public virtual bool isUseCastKeyword() {
return ((this.keyword != default!) && !((this.keyword.Length == 0)));
}

public virtual void setUseCastKeyword(bool useCastKeyword) {
if (useCastKeyword) {
if (((this.keyword == default!) || (this.keyword.Length == 0))) {
this.keyword = "CAST";
}
} else {
this.keyword = default!;
}
}

public virtual string getFormat() {
return this.format;
}

public virtual global::DripSharp.SqlTrellis.Expression.CastExpression setFormat(string format) {
this.format = format;
return this;
}

public override string ToString() {
string formatStr = (((this.format != default!) && !((this.format.Length == 0))) ? global::DripSharp.Runtime.JavaCompat.Concat(" FORMAT ", this.format) : "");
if (this.__field_isImplicitCast) {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.colDataType, " "), this.leftExpression);
} else {
if (((this.keyword != default!) && !((this.keyword.Length == 0)))) {
return ((global::DripSharp.Runtime.JavaCompat.CollectionCount(this.columnDefinitions) > 1) ? global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.keyword, "("), this.leftExpression), " AS ROW("), global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(this.columnDefinitions))), ")"), formatStr), ")") : global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.keyword, "("), this.leftExpression), " AS "), this.colDataType.ToString()), formatStr), ")"));
} else {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.leftExpression, "::"), this.colDataType.ToString());
}
}
}

public virtual global::DripSharp.SqlTrellis.Expression.CastExpression withType(global::DripSharp.SqlTrellis.Statement.Create.Table.ColDataType type) {
this.setColDataType(type);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.CastExpression withUseCastKeyword(bool useCastKeyword) {
this.setUseCastKeyword(useCastKeyword);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.CastExpression withLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression) {
this.setLeftExpression(leftExpression);
return this;
}

public virtual E getLeftExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getLeftExpression());
}

public virtual bool isOf(global::DripSharp.SqlTrellis.Expression.CastExpression anotherCast) {
return this.colDataType.Equals(anotherCast.colDataType);
}

public virtual bool isOf(params global::DripSharp.SqlTrellis.Expression.CastExpression.DataType[] types) {
return global::DripSharp.Runtime.JavaCompat.CollectionContains(global::DripSharp.Runtime.JavaCompat.EnumSetOf<global::DripSharp.SqlTrellis.Expression.CastExpression.DataType>(types), global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.from(this.colDataType.getDataType()));
}

public virtual bool isTime() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isTime(this.colDataType);
}

public virtual bool isTimeStamp() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isTimeStamp(this.colDataType);
}

public virtual bool isDate() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isDate(this.colDataType);
}

public virtual bool isBLOB() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isBLOB(this.colDataType);
}

public virtual bool isFloat() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isFloat(this.colDataType);
}

public virtual bool isInteger() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isInteger(this.colDataType);
}

public virtual bool isDecimal() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isDecimal(this.colDataType);
}

public virtual bool isText() {
return global::DripSharp.SqlTrellis.Expression.CastExpression.isText(this.colDataType);
}

public sealed class DataType {
[global::DripSharp.Runtime.JavaEnumNameAttribute("ARRAY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType ARRAY = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BIT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BIT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BITSTRING")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BITSTRING = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BLOB")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BLOB = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BYTEA")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(4)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BYTEA = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BINARY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(5)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BINARY = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("VARBINARY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(6)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType VARBINARY = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BYTES")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(7)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BYTES = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BOOLEAN")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(8)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BOOLEAN = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BOOL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(9)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BOOL = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("ENUM")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(10)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType ENUM = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INTERVAL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(11)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INTERVAL = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("LIST")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(12)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType LIST = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("MAP")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(13)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType MAP = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("STRUCT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(14)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType STRUCT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TINYINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(15)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TINYINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INT1")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(16)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INT1 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("SMALLINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(17)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType SMALLINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INT2")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(18)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INT2 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("SHORT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(19)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType SHORT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INTEGER")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(20)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INTEGER = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INT4")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(21)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INT4 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(22)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("SIGNED")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(23)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType SIGNED = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BIGINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(24)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BIGINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("INT8")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(25)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType INT8 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("LONG")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(26)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType LONG = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("HUGEINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(27)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType HUGEINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("UTINYINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(28)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType UTINYINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("USMALLINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(29)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType USMALLINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("UINTEGER")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(30)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType UINTEGER = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("UBIGINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(31)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType UBIGINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("UHUGEINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(32)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType UHUGEINT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("DECIMAL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(33)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType DECIMAL = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("NUMBER")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(34)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType NUMBER = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("NUMERIC")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(35)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType NUMERIC = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("REAL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(36)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType REAL = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FLOAT4")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(37)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType FLOAT4 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FLOAT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(38)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType FLOAT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("DOUBLE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(39)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType DOUBLE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("DOUBLE_PRECISION")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(40)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType DOUBLE_PRECISION = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FLOAT8")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(41)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType FLOAT8 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FLOAT64")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(42)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType FLOAT64 = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("UUID")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(43)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType UUID = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("VARCHAR")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(44)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType VARCHAR = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("NVARCHAR")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(45)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType NVARCHAR = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("CHAR")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(46)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType CHAR = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("NCHAR")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(47)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType NCHAR = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BPCHAR")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(48)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType BPCHAR = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("STRING")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(49)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType STRING = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TEXT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(50)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TEXT = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("CLOB")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(51)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType CLOB = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("DATE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(52)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType DATE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIME")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(53)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIME = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIME_WITHOUT_TIME_ZONE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(54)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIME_WITHOUT_TIME_ZONE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMETZ")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(55)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMETZ = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIME_WITH_TIME_ZONE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(56)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIME_WITH_TIME_ZONE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMP_NS")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(57)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMP_NS = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMP")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(58)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMP = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMP_WITHOUT_TIME_ZONE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(59)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMP_WITHOUT_TIME_ZONE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("DATETIME")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(60)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType DATETIME = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMP_MS")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(61)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMP_MS = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMP_S")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(62)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMP_S = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMPTZ")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(63)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMPTZ = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TIMESTAMP_WITH_TIME_ZONE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(64)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType TIMESTAMP_WITH_TIME_ZONE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("UNKNOWN")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(65)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType UNKNOWN = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("VARBYTE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(66)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType VARBYTE = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("JSON")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(67)]
public static readonly global::DripSharp.SqlTrellis.Expression.CastExpression.DataType JSON = new global::DripSharp.SqlTrellis.Expression.CastExpression.DataType();

public static global::DripSharp.SqlTrellis.Expression.CastExpression.DataType from(string typeStr) {
global::DripSharp.Runtime.JavaRegexMatcher matcher = global::DripSharp.Runtime.JavaCompat.RegexMatcher(global::DripSharp.SqlTrellis.Expression.CastExpression.PATTERN, global::DripSharp.Runtime.JavaCompat.StringReplaceAll(global::DripSharp.Runtime.JavaCompat.StringTrim(typeStr), "\\s+", "_").ToUpper());
if (matcher.Find()) {
try {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Expression.CastExpression.DataType>(matcher.Group(0));
} catch (global::System.Exception ex) when (ex is not global::System.TypeInitializationException) {
global::DripSharp.Runtime.JavaLogger.GetLogger((typeof(global::DripSharp.SqlTrellis.Expression.CastExpression).FullName ?? typeof(global::DripSharp.SqlTrellis.Expression.CastExpression).Name)).Log(global::DripSharp.Runtime.JavaLogLevel.Fine, global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Type ", typeStr), " unknown"), ex);
return global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.UNKNOWN;
}
} else {
global::DripSharp.Runtime.JavaLogger.GetLogger((typeof(global::DripSharp.SqlTrellis.Expression.CastExpression).FullName ?? typeof(global::DripSharp.SqlTrellis.Expression.CastExpression).Name)).Log(global::DripSharp.Runtime.JavaLogLevel.Fine, global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Type ", typeStr), " unknown"));
return global::DripSharp.SqlTrellis.Expression.CastExpression.DataType.UNKNOWN;
}
}

private DataType() {}


public static DataType[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<DataType>();
public static DataType valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<DataType>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
