// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/CollateExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class CollateExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private global::DripSharp.SqlTrellis.Expression.Expression leftExpression = null!;

private string collate = null!;

public CollateExpression() {}

public CollateExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression, string collate) {
this.leftExpression = leftExpression;
this.collate = collate;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getLeftExpression() {
return this.leftExpression;
}

public virtual void setLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression) {
this.leftExpression = leftExpression;
}

public virtual string getCollate() {
return this.collate;
}

public virtual void setCollate(string collate) {
this.collate = collate;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.leftExpression), " COLLATE "), this.collate);
}

public virtual global::DripSharp.SqlTrellis.Expression.CollateExpression withLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression) {
this.setLeftExpression(leftExpression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.CollateExpression withCollate(string collate) {
this.setCollate(collate);
return this;
}

public virtual E getLeftExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getLeftExpression());
}
}
