// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/DoubleValue.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class DoubleValue : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private double? value = default;

private string stringValue = null!;

public DoubleValue() {}

public DoubleValue(string value) {
if (((value == default!) || (value.Length == 0))) {
throw new global::System.ArgumentException("value can neither be null nor empty.");
}
string val = value;
if (((int)(val[0]) == (int)('+'))) {
val = val.Substring(1);
}
this.value = global::DripSharp.Runtime.JavaCompat.ParseDouble(val);
this.stringValue = val;
}

public DoubleValue(double value) {
this.value = value;
this.stringValue = global::DripSharp.Runtime.JavaCompat.StringValueOf(value);
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public virtual double getValue() {
return global::DripSharp.Runtime.JavaCompat.UnboxObject<double>(this.value);
}

public virtual void setValue(double? d) {
this.value = d;
this.stringValue = global::DripSharp.Runtime.JavaCompat.StringValueOf(this.value);
}

public override string ToString() {
return this.stringValue;
}

public virtual global::DripSharp.SqlTrellis.Expression.DoubleValue withValue(double? value) {
this.setValue(value);
return this;
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
