// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/ExtractExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class ExtractExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private string name = null!;

private global::DripSharp.SqlTrellis.Expression.Expression expression = null!;

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public virtual string getName() {
return this.name;
}

public virtual void setName(string name) {
this.name = name;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getExpression() {
return this.expression;
}

public virtual void setExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.expression = expression;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("EXTRACT(", this.name), " FROM "), this.expression), ')');
}

public virtual global::DripSharp.SqlTrellis.Expression.ExtractExpression withName(string name) {
this.setName(name);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.ExtractExpression withExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.setExpression(expression);
return this;
}

public virtual E getExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getExpression());
}
}
