// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/JdbcParameter.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class JdbcParameter : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private string parameterCharacter = "?";

private int? index = default;

private bool useFixedIndex = false;

public JdbcParameter() {}

public JdbcParameter(int? index, bool useFixedIndex, string parameterCharacter) {
this.index = index;
this.useFixedIndex = useFixedIndex;
this.parameterCharacter = parameterCharacter;
global::System.Text.RegularExpressions.Regex pattern = global::DripSharp.Runtime.JavaCompat.CompileRegex("(\\$)(\\d*)");
global::DripSharp.Runtime.JavaRegexMatcher matcher = global::DripSharp.Runtime.JavaCompat.RegexMatcher(pattern, parameterCharacter);
if ((matcher.Find() && (matcher.GroupCount() == 2))) {
this.useFixedIndex = true;
this.parameterCharacter = matcher.Group(1);
this.index = global::DripSharp.Runtime.JavaCompat.ParseInt(matcher.Group(2), 10);
}
}

public virtual string getParameterCharacter() {
return this.parameterCharacter;
}

public virtual global::DripSharp.SqlTrellis.Expression.JdbcParameter setParameterCharacter(string parameterCharacter) {
this.parameterCharacter = parameterCharacter;
return this;
}

public virtual int? getIndex() {
return this.index;
}

public virtual void setIndex(int? index) {
this.index = index;
}

public virtual bool isUseFixedIndex() {
return this.useFixedIndex;
}

public virtual void setUseFixedIndex(bool useFixedIndex) {
this.useFixedIndex = useFixedIndex;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
return (this.useFixedIndex ? global::DripSharp.Runtime.JavaCompat.Concat(this.parameterCharacter, this.index) : this.parameterCharacter);
}

public virtual global::DripSharp.SqlTrellis.Expression.JdbcParameter withIndex(int? index) {
this.setIndex(index);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.JdbcParameter withUseFixedIndex(bool useFixedIndex) {
this.setUseFixedIndex(useFixedIndex);
return this;
}
}
