// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/JsonFunctionExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class JsonFunctionExpression {
private readonly global::DripSharp.SqlTrellis.Expression.Expression expression = null!;

private bool usingFormatJson = false;

public JsonFunctionExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.expression = global::DripSharp.Runtime.JavaCompat.RequireNonNull(expression, "The EXPRESSION must not be null");
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getExpression() {
return this.expression;
}

public virtual bool isUsingFormatJson() {
return this.usingFormatJson;
}

public virtual void setUsingFormatJson(bool usingFormatJson) {
this.usingFormatJson = usingFormatJson;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonFunctionExpression withUsingFormatJson(bool usingFormatJson) {
this.setUsingFormatJson(usingFormatJson);
return this;
}

public virtual global::System.Text.StringBuilder append(global::System.Text.StringBuilder builder) {
return builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.getExpression())).Append((this.isUsingFormatJson() ? " FORMAT JSON" : ""));
}

public override string ToString() {
return this.append(new global::System.Text.StringBuilder()).ToString();
}
}
