// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/JsonAggregateFunction.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class JsonAggregateFunction : global::DripSharp.SqlTrellis.Expression.FilterOverImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private readonly global::DripSharp.SqlTrellis.Expression.OrderByClause expressionOrderBy = new global::DripSharp.SqlTrellis.Expression.OrderByClause();

private global::DripSharp.SqlTrellis.Expression.JsonFunctionType functionType = null!;

private global::DripSharp.SqlTrellis.Expression.Expression expression = default!;

private bool usingKeyKeyword = false;

private object key = null!;

private bool usingValueKeyword = false;

private object value = null!;

private bool usingFormatJson = false;

private global::DripSharp.SqlTrellis.Expression.JsonAggregateOnNullType onNullType = null!;

private global::DripSharp.SqlTrellis.Expression.JsonAggregateUniqueKeysType uniqueKeysType = null!;

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateOnNullType getOnNullType() {
return this.onNullType;
}

public virtual void setOnNullType(global::DripSharp.SqlTrellis.Expression.JsonAggregateOnNullType onNullType) {
this.onNullType = onNullType;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withOnNullType(global::DripSharp.SqlTrellis.Expression.JsonAggregateOnNullType onNullType) {
this.setOnNullType(onNullType);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateUniqueKeysType getUniqueKeysType() {
return this.uniqueKeysType;
}

public virtual void setUniqueKeysType(global::DripSharp.SqlTrellis.Expression.JsonAggregateUniqueKeysType uniqueKeysType) {
this.uniqueKeysType = uniqueKeysType;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withUniqueKeysType(global::DripSharp.SqlTrellis.Expression.JsonAggregateUniqueKeysType uniqueKeysType) {
this.setUniqueKeysType(uniqueKeysType);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonFunctionType getType() {
return this.functionType;
}

public virtual void setType(global::DripSharp.SqlTrellis.Expression.JsonFunctionType type) {
this.functionType = global::DripSharp.Runtime.JavaCompat.RequireNonNull(type, "The Type of the JSON Aggregate Function must not be null");
}

public virtual void setType(string typeName) {
this.functionType = global::DripSharp.SqlTrellis.Expression.JsonFunctionType.valueOf(global::DripSharp.Runtime.JavaCompat.RequireNonNull(typeName, "The Type of the JSON Aggregate Function must not be null").ToUpper());
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withType(global::DripSharp.SqlTrellis.Expression.JsonFunctionType type) {
this.setType(type);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withType(string typeName) {
this.setType(typeName);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getExpression() {
return this.expression;
}

public virtual void setExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.expression = expression;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.setExpression(expression);
return this;
}

public virtual bool isUsingKeyKeyword() {
return this.usingKeyKeyword;
}

public virtual void setUsingKeyKeyword(bool usingKeyKeyword) {
this.usingKeyKeyword = usingKeyKeyword;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withUsingKeyKeyword(bool usingKeyKeyword) {
this.setUsingKeyKeyword(usingKeyKeyword);
return this;
}

public virtual object getKey() {
return this.key;
}

public virtual void setKey(object key) {
this.key = key;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withKey(object key) {
this.setKey(key);
return this;
}

public virtual bool isUsingValueKeyword() {
return this.usingValueKeyword;
}

public virtual void setUsingValueKeyword(bool usingValueKeyword) {
this.usingValueKeyword = usingValueKeyword;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withUsingValueKeyword(bool usingValueKeyword) {
this.setUsingValueKeyword(usingValueKeyword);
return this;
}

public virtual object getValue() {
return this.value;
}

public virtual void setValue(object value) {
this.value = value;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withValue(object value) {
this.setValue(value);
return this;
}

public virtual bool isUsingFormatJson() {
return this.usingFormatJson;
}

public virtual void setUsingFormatJson(bool usingFormatJson) {
this.usingFormatJson = usingFormatJson;
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withUsingFormatJson(bool usingFormatJson) {
this.setUsingFormatJson(usingFormatJson);
return this;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> getExpressionOrderByElements() {
return this.expressionOrderBy.getOrderByElements();
}

public virtual void setExpressionOrderByElements(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
this.expressionOrderBy.setOrderByElements(orderByElements);
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction withExpressionOrderByElements(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.OrderByElement> orderByElements) {
this.setExpressionOrderByElements(orderByElements);
return this;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override global::System.Text.StringBuilder append(global::System.Text.StringBuilder builder) {
switch (global::DripSharp.Runtime.JavaCompat.EnumOrdinal(this.functionType)) {
case 0:
case 3:
this.appendObject(builder);
break;
case 1:
this.appendArray(builder);
break;
default:
throw new global::System.NotSupportedException(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("JSON Aggregate Function of the type ", global::DripSharp.Runtime.JavaCompat.EnumName(this.functionType)), " has not been implemented yet."));
}
return builder;
}

public virtual global::System.Text.StringBuilder appendObject(global::System.Text.StringBuilder builder) {
builder.Append("JSON_OBJECTAGG( ");
if (this.usingValueKeyword) {
if (this.usingKeyKeyword) {
builder.Append("KEY ");
}
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.key)).Append(" VALUE ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.value));
} else {
if ((this.functionType == global::DripSharp.SqlTrellis.Expression.JsonFunctionType.MYSQL_OBJECT)) {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.key)).Append(", ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.value));
} else {
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.key)).Append(":").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.value));
}
}
if (this.usingFormatJson) {
builder.Append(" FORMAT JSON");
}
if ((this.onNullType != default!)) {
switch (global::DripSharp.Runtime.JavaCompat.EnumOrdinal(this.onNullType)) {
case 0:
builder.Append(" NULL ON NULL");
break;
case 1:
builder.Append(" ABSENT On NULL");
break;
default:
break;
}
}
if ((this.uniqueKeysType != default!)) {
switch (global::DripSharp.Runtime.JavaCompat.EnumOrdinal(this.uniqueKeysType)) {
case 0:
builder.Append(" WITH UNIQUE KEYS");
break;
case 1:
builder.Append(" WITHOUT UNIQUE KEYS");
break;
default:
break;
}
}
builder.Append(" ) ");
base.append(builder);
return builder;
}

public virtual global::System.Text.StringBuilder appendArray(global::System.Text.StringBuilder builder) {
builder.Append("JSON_ARRAYAGG( ");
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.expression)).Append(" ");
if (this.usingFormatJson) {
builder.Append("FORMAT JSON ");
}
this.expressionOrderBy.toStringOrderByElements(builder);
if ((this.onNullType != default!)) {
switch (global::DripSharp.Runtime.JavaCompat.EnumOrdinal(this.onNullType)) {
case 0:
builder.Append(" NULL ON NULL ");
break;
case 1:
builder.Append(" ABSENT On NULL ");
break;
default:
break;
}
}
builder.Append(") ");
base.append(builder);
return builder;
}

public override string ToString() {
global::System.Text.StringBuilder builder = new global::System.Text.StringBuilder();
return this.append(builder).ToString();
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
