// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/JsonExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class JsonExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private readonly global::System.Collections.Generic.IList<global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string>> idents = new global::System.Collections.Generic.List<global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string>>();

private global::DripSharp.SqlTrellis.Expression.Expression expr = null!;

public JsonExpression() {}

public JsonExpression(global::DripSharp.SqlTrellis.Expression.Expression expr) {
this.expr = expr;
}

public JsonExpression(global::DripSharp.SqlTrellis.Expression.Expression expr, global::System.Collections.Generic.IList<global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string>> idents) {
this.expr = expr;
global::DripSharp.Runtime.JavaCompat.AddAll(this.idents, idents);
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getExpression() {
return this.expr;
}

public virtual void setExpression(global::DripSharp.SqlTrellis.Expression.Expression expr) {
this.expr = expr;
}

public virtual void addIdent(global::DripSharp.SqlTrellis.Expression.Expression ident, string @operator) {
global::DripSharp.Runtime.JavaCompat.Add(this.idents, new global::DripSharp.Runtime.JavaSimpleEntry<global::DripSharp.SqlTrellis.Expression.Expression, string>(ident, @operator));
}

public virtual void addAllIdents(global::System.Collections.Generic.ICollection<global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string>> idents) {
global::DripSharp.Runtime.JavaCompat.AddAll(this.idents, idents);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string>> getIdentList() {
return this.idents;
}

public virtual global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string> getIdent(int index) {
return global::DripSharp.Runtime.JavaCompat.ListGet(this.idents, index);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Expression.Expression> getIdents() {
global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Expression.Expression> l = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Expression.Expression>();
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string> ident in this.idents) {
global::DripSharp.Runtime.JavaCompat.Add(l, ident.Key);
}
return l;
}

public virtual global::System.Collections.Generic.IList<string> getOperators() {
global::System.Collections.Generic.List<string> l = new global::System.Collections.Generic.List<string>();
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string> ident in this.idents) {
global::DripSharp.Runtime.JavaCompat.Add(l, ident.Value);
}
return l;
}

public override string ToString() {
global::System.Text.StringBuilder b = new global::System.Text.StringBuilder();
b.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.expr));
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.SqlTrellis.Expression.Expression, string> ident in this.idents) {
b.Append(ident.Value).Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(ident.Key));
}
return b.ToString();
}

public virtual global::DripSharp.SqlTrellis.Expression.JsonExpression withExpression(global::DripSharp.SqlTrellis.Expression.Expression expr) {
this.setExpression(expr);
return this;
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
