// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/OracleHierarchicalExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class OracleHierarchicalExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
internal bool connectFirst = false;

private global::DripSharp.SqlTrellis.Expression.Expression startExpression = null!;

private global::DripSharp.SqlTrellis.Expression.Expression connectExpression = null!;

private bool noCycle = false;

public virtual global::DripSharp.SqlTrellis.Expression.Expression getStartExpression() {
return this.startExpression;
}

public virtual void setStartExpression(global::DripSharp.SqlTrellis.Expression.Expression startExpression) {
this.startExpression = startExpression;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getConnectExpression() {
return this.connectExpression;
}

public virtual void setConnectExpression(global::DripSharp.SqlTrellis.Expression.Expression connectExpression) {
this.connectExpression = connectExpression;
}

public virtual bool isNoCycle() {
return this.noCycle;
}

public virtual void setNoCycle(bool noCycle) {
this.noCycle = noCycle;
}

public virtual bool isConnectFirst() {
return this.connectFirst;
}

public virtual void setConnectFirst(bool connectFirst) {
this.connectFirst = connectFirst;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
global::System.Text.StringBuilder b = new global::System.Text.StringBuilder();
if (this.isConnectFirst()) {
b.Append(" CONNECT BY ");
if (this.isNoCycle()) {
b.Append("NOCYCLE ");
}
b.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.connectExpression));
if ((this.startExpression != default!)) {
b.Append(" START WITH ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.startExpression));
}
} else {
if ((this.startExpression != default!)) {
b.Append(" START WITH ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.startExpression));
}
b.Append(" CONNECT BY ");
if (this.isNoCycle()) {
b.Append("NOCYCLE ");
}
b.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.connectExpression));
}
return b.ToString();
}

public virtual global::DripSharp.SqlTrellis.Expression.OracleHierarchicalExpression withStartExpression(global::DripSharp.SqlTrellis.Expression.Expression startExpression) {
this.setStartExpression(startExpression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.OracleHierarchicalExpression withConnectExpression(global::DripSharp.SqlTrellis.Expression.Expression connectExpression) {
this.setConnectExpression(connectExpression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.OracleHierarchicalExpression withNoCycle(bool noCycle) {
this.setNoCycle(noCycle);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.OracleHierarchicalExpression withConnectFirst(bool connectFirst) {
this.setConnectFirst(connectFirst);
return this;
}

public virtual E getStartExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getStartExpression());
}

public virtual E getConnectExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getConnectExpression());
}
}
