// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/RowConstructor.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class RowConstructor<T> : global::DripSharp.SqlTrellis.Expression.Operators.Relational.ParenthesedExpressionList<T>, global::DripSharp.SqlTrellis.Expression.Expression where T : global::DripSharp.SqlTrellis.Expression.Expression {
private string name = default!;

public RowConstructor() {}

public RowConstructor(string name, global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> expressionList) {
this.name = name;
global::DripSharp.Runtime.JavaCompat.AddAll(this, expressionList);
}

public virtual string getName() {
return this.name;
}

public virtual void setName(string name) {
this.name = name;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(((this.name != default!) ? this.name : ""), base.ToString());
}

public virtual global::DripSharp.SqlTrellis.Expression.RowConstructor<T> withName(string name) {
this.setName(name);
return this;
}

public override K accept<K, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<K> expressionVisitor, S context) {
return expressionVisitor.visit<S, T>(this, context);
}
}
