// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/StringValue.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public sealed class StringValue : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
public static readonly global::System.Collections.Generic.IList<string> ALLOWED_PREFIXES = global::DripSharp.Runtime.JavaCompat.AsList<string>("N", "U", "E", "R", "B", "RB", "_utf8", "Q");

private string value = "";

private string prefix = default!;

public StringValue() {}

public StringValue(string escapedValue) {
if ((((escapedValue.Length >= 2) && global::DripSharp.Runtime.JavaCompat.StringStartsWith(escapedValue, "'")) && global::DripSharp.Runtime.JavaCompat.StringEndsWith(escapedValue, "'"))) {
this.value = global::DripSharp.Runtime.JavaCompat.StringSubstring(escapedValue, 1, (escapedValue.Length - 1));
return;
}
if ((escapedValue.Length > 2)) {
foreach (string p in global::DripSharp.SqlTrellis.Expression.StringValue.ALLOWED_PREFIXES) {
if ((((escapedValue.Length > p.Length) && global::DripSharp.Runtime.JavaCompat.EqualsIgnoreCase(global::DripSharp.Runtime.JavaCompat.StringSubstring(escapedValue, 0, p.Length), p)) && ((int)(escapedValue[p.Length]) == (int)('\'')))) {
this.prefix = p;
this.value = global::DripSharp.Runtime.JavaCompat.StringSubstring(escapedValue, (p.Length + 1), (escapedValue.Length - 1));
return;
}
}
}
this.value = escapedValue;
}

public string getValue() {
return this.value;
}

public void setValue(string @string) {
this.value = @string;
}

public string getPrefix() {
return this.prefix;
}

public void setPrefix(string prefix) {
this.prefix = prefix;
}

public string getNotExcapedValue() {
global::System.Text.StringBuilder buffer = new global::System.Text.StringBuilder(this.value);
int index = 0;
int deletesNum = 0;
while (((index = this.value.IndexOf("''", index, global::System.StringComparison.Ordinal)) != -1)) {
buffer.Remove((index - deletesNum), 1);
index += 2;
deletesNum++;
}
return buffer.ToString();
}

public T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(((this.prefix != default!) ? this.prefix : ""), "'"), this.value), "'");
}

public global::DripSharp.SqlTrellis.Expression.StringValue withPrefix(string prefix) {
this.setPrefix(prefix);
return this;
}

public global::DripSharp.SqlTrellis.Expression.StringValue withValue(string value) {
this.setValue(value);
return this;
}

public override bool Equals(object o) {
if ((this == o)) {
return true;
}
if (((o == default!) || (((object)(this)).GetType() != ((object)(o)).GetType()))) {
return false;
}
global::DripSharp.SqlTrellis.Expression.StringValue that = (global::DripSharp.SqlTrellis.Expression.StringValue)(o!);
return (global::DripSharp.Runtime.JavaCompat.Equals(this.value, that.value) && global::DripSharp.Runtime.JavaCompat.Equals(this.prefix, that.prefix));
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.value, this.prefix);
}
}
