// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/WindowRange.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression;

public class WindowRange {
private global::DripSharp.SqlTrellis.Expression.WindowOffset start = null!;

private global::DripSharp.SqlTrellis.Expression.WindowOffset end = null!;

public virtual global::DripSharp.SqlTrellis.Expression.WindowOffset getEnd() {
return this.end;
}

public virtual void setEnd(global::DripSharp.SqlTrellis.Expression.WindowOffset end) {
this.end = end;
}

public virtual global::DripSharp.SqlTrellis.Expression.WindowOffset getStart() {
return this.start;
}

public virtual void setStart(global::DripSharp.SqlTrellis.Expression.WindowOffset start) {
this.start = start;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(" BETWEEN", this.start), " AND"), this.end);
}

public virtual global::DripSharp.SqlTrellis.Expression.WindowRange withStart(global::DripSharp.SqlTrellis.Expression.WindowOffset start) {
this.setStart(start);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.WindowRange withEnd(global::DripSharp.SqlTrellis.Expression.WindowOffset end) {
this.setEnd(end);
return this;
}
}
