// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/operators/relational/ExpressionList.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression.Operators.Relational;

public class ExpressionList<T> : global::System.Collections.Generic.List<T>, global::DripSharp.SqlTrellis.Expression.Expression where T : global::DripSharp.SqlTrellis.Expression.Expression {
private global::DripSharp.SqlTrellis.Parser.SimpleNode node = null!;

public ExpressionList(global::System.Collections.Generic.ICollection<T> expressions) {
global::DripSharp.Runtime.JavaCompat.AddAll(this, expressions);
}

public ExpressionList(global::System.Collections.Generic.IList<T> expressions) : base(expressions) {

}

public ExpressionList(params T[] expressions) : this(global::DripSharp.Runtime.JavaCompat.AsList<T>(expressions)) {

}

public virtual bool isUsingBrackets() {
return false;
}

public virtual global::System.Collections.Generic.IList<T> getExpressions() {
return this;
}

public virtual void setExpressions(global::System.Collections.Generic.IList<T> expressions) {
this.Clear();
global::DripSharp.Runtime.JavaCompat.AddAll(this, expressions);
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> addExpression(T expression) {
global::DripSharp.Runtime.JavaCompat.Add(this, expression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> addExpressions(params T[] expressions) {
global::DripSharp.Runtime.JavaCompat.AddAll(this, global::DripSharp.Runtime.JavaCompat.AsList<T>(expressions));
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> addExpressions(global::System.Collections.Generic.ICollection<T> expressions) {
global::DripSharp.Runtime.JavaCompat.AddAll(this, expressions);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> withExpressions(params T[] expressions) {
this.Clear();
return this.addExpressions(expressions);
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> withExpressions(global::System.Collections.Generic.ICollection<T> expressions) {
this.Clear();
return global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<T>(this.addExpressions(expressions));
}

public virtual global::System.Text.StringBuilder appendTo(global::System.Text.StringBuilder builder) {
for (int i = 0; (i < global::DripSharp.Runtime.JavaCompat.CollectionCount(this)); i++) {
if ((i > 0)) {
builder.Append(", ");
}
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(global::DripSharp.Runtime.JavaCompat.ListGet(this, i)));
}
return builder;
}

public override string ToString() {
return this.appendTo(new global::System.Text.StringBuilder()).ToString();
}

public virtual global::DripSharp.SqlTrellis.Parser.SimpleNode getASTNode() {
return this.node;
}

public virtual void setASTNode(global::DripSharp.SqlTrellis.Parser.SimpleNode node) {
this.node = node;
}

public virtual K accept<K, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<K> expressionVisitor, S context) {
return expressionVisitor.visit<S, T>(this, context);
}
}
