// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/operators/relational/FullTextSearch.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression.Operators.Relational;

public class FullTextSearch : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> _matchColumns = null!;

private global::DripSharp.SqlTrellis.Expression.Expression _againstValue = null!;

private string _searchModifier = null!;

public FullTextSearch() {}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> getMatchColumns() {
return this._matchColumns;
}

public virtual void setMatchColumns(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> columns) {
this._matchColumns = columns;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getAgainstValue() {
return this._againstValue;
}

public virtual void setAgainstValue(global::DripSharp.SqlTrellis.Expression.StringValue val) {
this._againstValue = val;
}

public virtual void setAgainstValue(global::DripSharp.SqlTrellis.Expression.JdbcNamedParameter val) {
this._againstValue = val;
}

public virtual void setAgainstValue(global::DripSharp.SqlTrellis.Expression.JdbcParameter val) {
this._againstValue = val;
}

public virtual string getSearchModifier() {
return this._searchModifier;
}

public virtual void setSearchModifier(string val) {
this._searchModifier = val;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
string columnsListCommaSeperated = "";
global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Schema.Column> iterator = global::DripSharp.Runtime.JavaCompat.Iterator(this._matchColumns);
while (iterator.HasNext()) {
global::DripSharp.SqlTrellis.Schema.Column col = iterator.Next()!;
columnsListCommaSeperated += col.getFullyQualifiedName();
if (iterator.HasNext()) {
columnsListCommaSeperated += ",";
}
}
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("MATCH (", columnsListCommaSeperated), ") AGAINST ("), this._againstValue), ((this._searchModifier != default!) ? global::DripSharp.Runtime.JavaCompat.Concat(" ", this._searchModifier) : "")), ")");
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch withMatchColumns(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> matchColumns) {
this.setMatchColumns(matchColumns);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch withAgainstValue(global::DripSharp.SqlTrellis.Expression.StringValue againstValue) {
this.setAgainstValue(againstValue);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch withSearchModifier(string searchModifier) {
this.setSearchModifier(searchModifier);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch addMatchColumns(params global::DripSharp.SqlTrellis.Schema.Column[] matchColumns) {
return this.addMatchColumns(global::DripSharp.Runtime.JavaCompat.AsList<global::DripSharp.SqlTrellis.Schema.Column>(matchColumns));
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch addMatchColumns(global::System.Collections.Generic.ICollection<global::DripSharp.SqlTrellis.Schema.Column> matchColumns) {
global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column> collection = global::DripSharp.Runtime.JavaOptional<global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column>>.OfNullable(this.getMatchColumns()).OrElseGet(() => new global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Schema.Column>());
global::DripSharp.Runtime.JavaCompat.AddAll(collection, matchColumns);
return this.withMatchColumns(collection);
}
}
