// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/operators/relational/IncludesExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression.Operators.Relational;

public class IncludesExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private global::DripSharp.SqlTrellis.Expression.Expression leftExpression = null!;

private global::DripSharp.SqlTrellis.Expression.Expression rightExpression = null!;

public IncludesExpression() {}

public IncludesExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression, global::DripSharp.SqlTrellis.Expression.Expression rightExpression) {
this.leftExpression = leftExpression;
this.rightExpression = rightExpression;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getLeftExpression() {
return this.leftExpression;
}

public void setLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.leftExpression = expression;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.IncludesExpression withLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.setLeftExpression(expression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getRightExpression() {
return this.rightExpression;
}

public virtual void setRightExpression(global::DripSharp.SqlTrellis.Expression.Expression rightExpression) {
this.rightExpression = rightExpression;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
global::System.Text.StringBuilder statementBuilder = new global::System.Text.StringBuilder();
statementBuilder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.leftExpression));
statementBuilder.Append(" ");
statementBuilder.Append("INCLUDES ");
statementBuilder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.rightExpression));
return statementBuilder.ToString();
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.IncludesExpression withRightExpression(global::DripSharp.SqlTrellis.Expression.Expression rightExpression) {
this.setRightExpression(rightExpression);
return this;
}

public virtual E getLeftExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getLeftExpression());
}

public virtual E getRightExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getRightExpression());
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
