// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/operators/relational/IsNullExpression.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression.Operators.Relational;

public class IsNullExpression : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression {
private global::DripSharp.SqlTrellis.Expression.Expression leftExpression = null!;

private bool not = false;

private bool useIsNull = false;

private bool useNotNull = false;

public IsNullExpression() {}

public IsNullExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression) {
this.leftExpression = leftExpression;
}

public IsNullExpression(string columnName, bool not) {
this.leftExpression = new global::DripSharp.SqlTrellis.Schema.Column(columnName);
this.not = not;
}

public virtual global::DripSharp.SqlTrellis.Expression.Expression getLeftExpression() {
return this.leftExpression;
}

public virtual void setLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression expression) {
this.leftExpression = expression;
}

public virtual bool isNot() {
return this.not;
}

public virtual void setNot(bool b) {
this.not = b;
}

public virtual bool isUseIsNull() {
return this.useIsNull;
}

public virtual void setUseIsNull(bool useIsNull) {
this.useIsNull = useIsNull;
}

public virtual bool isUseNotNull() {
return this.useNotNull;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsNullExpression setUseNotNull(bool useNotNull) {
this.useNotNull = useNotNull;
return this;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
if (this.useNotNull) {
return global::DripSharp.Runtime.JavaCompat.Concat(this.leftExpression, " NOTNULL");
} else {
if (this.useIsNull) {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.leftExpression, (this.not ? " NOT" : "")), " ISNULL");
} else {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.leftExpression, " IS "), (this.not ? "NOT " : "")), "NULL");
}
}
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsNullExpression withUseIsNull(bool useIsNull) {
this.setUseIsNull(useIsNull);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsNullExpression withLeftExpression(global::DripSharp.SqlTrellis.Expression.Expression leftExpression) {
this.setLeftExpression(leftExpression);
return this;
}

public virtual global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsNullExpression withNot(bool not) {
this.setNot(not);
return this;
}

public virtual E getLeftExpression<E>(global::System.Type type) where E : global::DripSharp.SqlTrellis.Expression.Expression {
return global::DripSharp.Runtime.JavaCompat.ClassCast<E>(type, this.getLeftExpression());
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
