// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/expression/operators/relational/ParenthesedExpressionList.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Expression.Operators.Relational;

public class ParenthesedExpressionList<T> : global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> where T : global::DripSharp.SqlTrellis.Expression.Expression {
public ParenthesedExpressionList() {}

public ParenthesedExpressionList(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<T> expressions) {
global::DripSharp.Runtime.JavaCompat.AddAll(this, expressions);
}

public ParenthesedExpressionList(params T[] expressions) {
global::DripSharp.Runtime.JavaCompat.AddAll(this, global::DripSharp.Runtime.JavaCompat.AsList<T>(expressions));
}

public ParenthesedExpressionList(global::System.Collections.Generic.ICollection<T> expressions) {
global::DripSharp.Runtime.JavaCompat.AddAll(this, expressions);
}

public static global::DripSharp.SqlTrellis.Expression.Operators.Relational.ParenthesedExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> from(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> expressions) {
return new global::DripSharp.SqlTrellis.Expression.Operators.Relational.ParenthesedExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<T>(expressions));
}

public override string ToString() {
return global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(this), true, true);
}
}
