// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/alter/AlterSystemOperation.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Alter;

public sealed class AlterSystemOperation {
[global::DripSharp.Runtime.JavaEnumNameAttribute("ARCHIVE_LOG")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation ARCHIVE_LOG = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("ARCHIVE LOG");

[global::DripSharp.Runtime.JavaEnumNameAttribute("CHECKPOINT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation CHECKPOINT = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("CHECKPOINT");

[global::DripSharp.Runtime.JavaEnumNameAttribute("CHECK_DATAFILES")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation CHECK_DATAFILES = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("CHECK DATAFILES");

[global::DripSharp.Runtime.JavaEnumNameAttribute("DUMP_ACTIVE_SESSION_HISTORY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation DUMP_ACTIVE_SESSION_HISTORY = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("DUMP ACTIVE SESSION HISTORY");

[global::DripSharp.Runtime.JavaEnumNameAttribute("ENABLE_DISTRIBUTED_RECOVERY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(4)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation ENABLE_DISTRIBUTED_RECOVERY = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("ENABLE DISTRIBUTED RECOVERY");

[global::DripSharp.Runtime.JavaEnumNameAttribute("DISABLE_DISTRIBUTED_RECOVERY")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(5)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation DISABLE_DISTRIBUTED_RECOVERY = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("DISABLE DISTRIBUTED RECOVERY");

[global::DripSharp.Runtime.JavaEnumNameAttribute("ENABLE_RESTRICTED_SESSION")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(6)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation ENABLE_RESTRICTED_SESSION = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("ENABLE RESTRICTED SESSION");

[global::DripSharp.Runtime.JavaEnumNameAttribute("DISABLE_RESTRICTED_SESSION")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(7)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation DISABLE_RESTRICTED_SESSION = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("DISABLE RESTRICTED SESSION");

[global::DripSharp.Runtime.JavaEnumNameAttribute("FLUSH")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(8)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation FLUSH = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("FLUSH");

[global::DripSharp.Runtime.JavaEnumNameAttribute("DISCONNECT_SESSION")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(9)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation DISCONNECT_SESSION = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("DISCONNECT SESSION");

[global::DripSharp.Runtime.JavaEnumNameAttribute("KILL_SESSION")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(10)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation KILL_SESSION = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("KILL SESSION");

[global::DripSharp.Runtime.JavaEnumNameAttribute("SWITCH")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(11)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation SWITCH = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("SWITCH");

[global::DripSharp.Runtime.JavaEnumNameAttribute("SUSPEND")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(12)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation SUSPEND = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("SUSPEND");

[global::DripSharp.Runtime.JavaEnumNameAttribute("RESUME")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(13)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation RESUME = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("RESUME");

[global::DripSharp.Runtime.JavaEnumNameAttribute("QUIESCE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(14)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation QUIESCE = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("QUIESCE RESTRICTED");

[global::DripSharp.Runtime.JavaEnumNameAttribute("UNQUIESCE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(15)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation UNQUIESCE = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("UNQUIESCE");

[global::DripSharp.Runtime.JavaEnumNameAttribute("SHUTDOWN")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(16)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation SHUTDOWN = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("SHUTDOWN");

[global::DripSharp.Runtime.JavaEnumNameAttribute("REGISTER")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(17)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation REGISTER = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("REGISTER");

[global::DripSharp.Runtime.JavaEnumNameAttribute("SET")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(18)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation SET = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("SET");

[global::DripSharp.Runtime.JavaEnumNameAttribute("RESET")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(19)]
public static readonly global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation RESET = new global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation("RESET");

private readonly string label = null!;

private AlterSystemOperation(string label) {
this.label = label;
}

public static global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation from(string operation) {
foreach (global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation alterSystemOperation in global::DripSharp.SqlTrellis.Statement.Alter.AlterSystemOperation.values()) {
if (global::DripSharp.Runtime.JavaCompat.Equals(alterSystemOperation.ToString(), operation)) {
return alterSystemOperation;
}
}
return default!;
}

public override string ToString() {
return this.label;
}

public static AlterSystemOperation[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<AlterSystemOperation>();
public static AlterSystemOperation valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<AlterSystemOperation>(name);
}
