// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/alter/ValidateConstraint.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement.Alter;

public class ValidateConstraint : global::DripSharp.SqlTrellis.Statement.Alter.ConstraintState {
private bool not = default;

public ValidateConstraint() {}

public ValidateConstraint(bool not) {
this.not = not;
}

public virtual bool isNot() {
return this.not;
}

public virtual void setNot(bool not) {
this.not = not;
}

public override string ToString() {
return (this.not ? "NOVALIDATE" : "VALIDATE");
}

public virtual global::DripSharp.SqlTrellis.Statement.Alter.ValidateConstraint withNot(bool not) {
this.setNot(not);
return this;
}
}
