// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/feature/FeatureContext.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Feature;

public sealed class FeatureContext : global::DripSharp.SqlTrellis.Util.Validation.ContextKey {
[global::DripSharp.Runtime.JavaEnumNameAttribute("feature")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Util.Validation.Feature.FeatureContext feature = new global::DripSharp.SqlTrellis.Util.Validation.Feature.FeatureContext();

private FeatureContext() {}


public static FeatureContext[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<FeatureContext>();
public static FeatureContext valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<FeatureContext>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
