// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/feature/FeatureSetValidation.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Feature;

public interface FeatureSetValidation : global::DripSharp.SqlTrellis.Parser.Feature.FeatureSet, global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability {
public const string DEFAULT_NAME = "feature set";

public new void validate(global::DripSharp.SqlTrellis.Util.Validation.ValidationContext context, global::System.Action<global::DripSharp.SqlTrellis.Util.Validation.ValidationException> errorConsumer) {
global::DripSharp.SqlTrellis.Parser.Feature.Feature feature = context.get<global::DripSharp.SqlTrellis.Parser.Feature.Feature>(global::DripSharp.SqlTrellis.Util.Validation.Feature.FeatureContext.feature, typeof(global::DripSharp.SqlTrellis.Parser.Feature.Feature));
if (!(((global::DripSharp.SqlTrellis.Parser.Feature.FeatureSet)(this)).contains(feature))) {
errorConsumer(this.getMessage(feature));
}
}

public new global::System.Collections.Generic.ISet<global::DripSharp.SqlTrellis.Parser.Feature.Feature> getFeatures();

public global::DripSharp.SqlTrellis.Util.Validation.ValidationException getMessage(global::DripSharp.SqlTrellis.Parser.Feature.Feature feature);

public new string getName() {
return global::DripSharp.SqlTrellis.Util.Validation.Feature.FeatureSetValidation.DEFAULT_NAME;
}

void global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability.validate(global::DripSharp.SqlTrellis.Util.Validation.ValidationContext context, global::System.Action<global::DripSharp.SqlTrellis.Util.Validation.ValidationException> errorConsumer) => this.validate(context, errorConsumer);

global::System.Collections.Generic.ISet<global::DripSharp.SqlTrellis.Parser.Feature.Feature> global::DripSharp.SqlTrellis.Parser.Feature.FeatureSet.getFeatures() => (this.getFeatures());

string global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability.getName() => (this.getName());
}
