<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>DripSharp.SqlTrellis.Tests</AssemblyName>
    <RootNamespace>DripSharp.SqlTrellis.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" PrivateAssets="all" />
    <PackageReference Include="xunit" Version="2.9.3" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all" />
    <PackageReference Include="Castle.Core" Version="5.1.1" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DripSharp.SqlTrellis/DripSharp.SqlTrellis.csproj" />
  </ItemGroup>
  <ItemGroup />
</Project>
