// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/JSQLParserException.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis;

public class JSQLParserException : global::System.Exception {
internal const long serialVersionUID = -4200894355696788796L;

public JSQLParserException() : base() {

}

public JSQLParserException(string message, global::System.Exception cause) : base(message, cause) {

}

public JSQLParserException(string message) : base(message) {

}

public JSQLParserException(global::System.Exception cause) : base(((cause == default!) ? (string)(default!) : global::DripSharp.Runtime.JavaCompat.ExceptionMessage(cause)), cause) {

}
}
