// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/DeclareType.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement;

public sealed class DeclareType {
[global::DripSharp.Runtime.JavaEnumNameAttribute("TABLE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.DeclareType TABLE = new global::DripSharp.SqlTrellis.Statement.DeclareType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("AS")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.DeclareType AS = new global::DripSharp.SqlTrellis.Statement.DeclareType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("TYPE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Statement.DeclareType TYPE = new global::DripSharp.SqlTrellis.Statement.DeclareType();

public static global::DripSharp.SqlTrellis.Statement.DeclareType from(string type) {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Statement.DeclareType>(type.ToUpper());
}

private DeclareType() {}


public static DeclareType[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<DeclareType>();
public static DeclareType valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<DeclareType>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
