// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/ExplainStatement.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement;

public class ExplainStatement : global::DripSharp.SqlTrellis.Statement.Statement {
private string keyword = null!;

private global::DripSharp.SqlTrellis.Statement.Select.Select select = null!;

private global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option> options = null!;

private global::DripSharp.SqlTrellis.Schema.Table table = null!;

public ExplainStatement(string keyword) {
this.keyword = keyword;
}

public ExplainStatement() : this("EXPLAIN") {

}

public ExplainStatement(string keyword, global::DripSharp.SqlTrellis.Schema.Table table) {
this.keyword = keyword;
this.table = table;
this.select = default!;
}

public ExplainStatement(string keyword, global::DripSharp.SqlTrellis.Statement.Select.Select select, global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option> optionList) {
this.keyword = keyword;
this.select = select;
this.table = default!;
if (((optionList != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(optionList)))) {
this.options = new global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option>();
foreach (global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option o in optionList) {
global::DripSharp.Runtime.JavaCompat.MapPut(this.options, o.getType(), o);
}
}
}

public ExplainStatement(global::DripSharp.SqlTrellis.Statement.Select.Select select) : this("EXPLAIN", select, (global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option>)default!) {

}

public virtual global::DripSharp.SqlTrellis.Schema.Table getTable() {
return this.table;
}

public virtual global::DripSharp.SqlTrellis.Statement.ExplainStatement setTable(global::DripSharp.SqlTrellis.Schema.Table table) {
this.table = table;
return this;
}

public virtual global::DripSharp.SqlTrellis.Statement.Select.Select getStatement() {
return this.select;
}

public virtual void setStatement(global::DripSharp.SqlTrellis.Statement.Select.Select select) {
this.select = select;
}

public virtual global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option> getOptions() {
return ((this.options == default!) ? (global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option>)(default!) : new global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option>(global::DripSharp.Runtime.JavaCompat.CastDictionary<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option>(this.options)));
}

public virtual void addOption(global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option option) {
if ((this.options == default!)) {
this.options = new global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType, global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option>();
}
global::DripSharp.Runtime.JavaCompat.MapPut(this.options, option.getType(), option);
}

public virtual global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option getOption(global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType optionType) {
if ((this.options == default!)) {
return default!;
}
return global::DripSharp.Runtime.JavaCompat.MapGet(this.options, optionType);
}

public virtual string getKeyword() {
return this.keyword;
}

public virtual global::DripSharp.SqlTrellis.Statement.ExplainStatement setKeyword(string keyword) {
this.keyword = keyword;
return this;
}

public override string ToString() {
global::System.Text.StringBuilder builder = new global::System.Text.StringBuilder(this.keyword);
if ((this.table != default!)) {
builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.table));
} else {
if ((this.options != default!)) {
builder.Append(" ");
builder.Append(global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(this.options.Values), (value0) => value0.formatOption()), global::DripSharp.Runtime.JavaCompat.Joining(" ")));
}
builder.Append(" ");
if ((this.select != default!)) {
this.select.appendTo(builder);
}
}
return builder.ToString();
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<T> statementVisitor, S context) {
return statementVisitor.visit(this, context);
}

public sealed class OptionType {
[global::DripSharp.Runtime.JavaEnumNameAttribute("ANALYZE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType ANALYZE = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("VERBOSE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType VERBOSE = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("COSTS")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType COSTS = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("BUFFERS")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType BUFFERS = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FORMAT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(4)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType FORMAT = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("PLAN")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(5)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType PLAN = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

[global::DripSharp.Runtime.JavaEnumNameAttribute("PLAN_FOR")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(6)]
public static readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType PLAN_FOR = new global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType();

public static global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType from(string type) {
return global::DripSharp.Runtime.JavaCompat.EnumValueOf<global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType>(type.ToUpper());
}

private OptionType() {}


public static OptionType[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<OptionType>();
public static OptionType valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<OptionType>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}

public class Option {
internal readonly global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType type = null!;

internal string value = null!;

public Option(global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType type) {
this.type = type;
}

public virtual global::DripSharp.SqlTrellis.Statement.ExplainStatement.OptionType getType() {
return this.type;
}

public virtual string getValue() {
return this.value;
}

public virtual void setValue(string value) {
this.value = value;
}

public virtual string formatOption() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.ReplaceOrdinal(global::DripSharp.Runtime.JavaCompat.EnumName(this.type), "_", " "), ((this.value != default!) ? global::DripSharp.Runtime.JavaCompat.Concat(" ", this.value) : ""));
}

public virtual global::DripSharp.SqlTrellis.Statement.ExplainStatement.Option withValue(string value) {
this.setValue(value);
return this;
}
}

public virtual void accept<TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<TWildcard0_0> statementVisitor) {
this.accept<TWildcard0_0, object>(statementVisitor, (object)default!);
}
}
