// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/statement/ShowStatement.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Statement;

public class ShowStatement : global::DripSharp.SqlTrellis.Statement.Statement {
private string name = null!;

public ShowStatement() {}

public ShowStatement(string name) {
this.name = name;
}

public virtual string getName() {
return this.name;
}

public virtual void setName(string name) {
this.name = name;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat("SHOW ", this.name);
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Statement.StatementVisitor<T> statementVisitor, S context) {
return statementVisitor.visit(this, context);
}

public virtual global::DripSharp.SqlTrellis.Statement.ShowStatement withName(string name) {
this.setName(name);
return this;
}
}
