// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/metadata/DatabaseException.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Metadata;

public class DatabaseException : global::DripSharp.SqlTrellis.Util.Validation.ValidationException {
internal new const long serialVersionUID = 1L;

public DatabaseException(string message, global::System.Exception cause) : base(message, cause) {

}

public DatabaseException(string message) : base(message) {

}

public DatabaseException(global::System.Exception cause) : base(cause) {

}
}
