// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/metadata/MetadataContext.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Metadata;

public sealed class MetadataContext : global::DripSharp.SqlTrellis.Util.Validation.ContextKey {
[global::DripSharp.Runtime.JavaEnumNameAttribute("named")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.SqlTrellis.Util.Validation.Metadata.MetadataContext named = new global::DripSharp.SqlTrellis.Util.Validation.Metadata.MetadataContext();

[global::DripSharp.Runtime.JavaEnumNameAttribute("exists")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.SqlTrellis.Util.Validation.Metadata.MetadataContext exists = new global::DripSharp.SqlTrellis.Util.Validation.Metadata.MetadataContext();

private MetadataContext() {}


public static MetadataContext[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<MetadataContext>();
public static MetadataContext valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<MetadataContext>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
