// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/metadata/Named.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Metadata;

public class Named {
private readonly global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject namedObject = null!;

private readonly string fqn = null!;

private string alias = null!;

private global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject> parents = null!;

private string fqnLookup = null!;

private string aliasLookup = null!;

public Named(global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject namedObject, string fqn) {
global::DripSharp.Runtime.JavaCompat.RequireNonNull(namedObject, "named object must not be null");
global::DripSharp.Runtime.JavaCompat.RequireNonNull(fqn, "fully qualified name must not be null");
this.namedObject = namedObject;
this.fqn = fqn;
}

public virtual string getFqn() {
return this.fqn;
}

public virtual string getAlias() {
return this.alias;
}

public virtual global::DripSharp.SqlTrellis.Util.Validation.Metadata.Named setAlias(string alias) {
this.alias = alias;
return this;
}

public virtual global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject getNamedObject() {
return this.namedObject;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject> getParents() {
return this.parents;
}

public virtual global::DripSharp.SqlTrellis.Util.Validation.Metadata.Named setParents(global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject> parents) {
this.parents = parents;
return this;
}

public virtual string getFqnLookup() {
return this.fqnLookup;
}

public virtual global::DripSharp.SqlTrellis.Util.Validation.Metadata.Named setFqnLookup(string fqnLookup) {
this.fqnLookup = fqnLookup;
return this;
}

public virtual string getAliasLookup() {
return this.aliasLookup;
}

public virtual global::DripSharp.SqlTrellis.Util.Validation.Metadata.Named setAliasLookup(string aliasLookup) {
this.aliasLookup = aliasLookup;
return this;
}

public override int GetHashCode() {
int prime = 31;
int result = 1;
result = ((prime * result) + ((this.alias == default!) ? 0 : global::DripSharp.Runtime.JavaCompat.HashCode(this.alias)));
result = ((prime * result) + global::DripSharp.Runtime.JavaCompat.HashCode(this.fqn));
result = ((prime * result) + this.namedObject.GetHashCode());
return result;
}

public override bool Equals(object obj) {
if ((this == obj)) {
return true;
}
if ((obj == default!)) {
return false;
}
if ((((object)(this)).GetType() != ((object)(obj)).GetType())) {
return false;
}
global::DripSharp.SqlTrellis.Util.Validation.Metadata.Named other = (global::DripSharp.SqlTrellis.Util.Validation.Metadata.Named)(obj!);
if ((this.alias == default!)) {
if ((other.alias != default!)) {
return false;
}
} else {
if (!(global::DripSharp.Runtime.JavaCompat.Equals(this.alias, other.alias))) {
return false;
}
}
if (!(global::DripSharp.Runtime.JavaCompat.Equals(this.fqn, other.fqn))) {
return false;
}
if ((this.namedObject != other.namedObject)) {
return false;
}
return true;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Named [namedObject=", this.namedObject), ", fqn="), this.fqn), ", alias="), this.alias), ", parents="), this.parents), "]");
}
}
