// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/schema/Column.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Schema;

public class Column : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Expression.Expression, global::DripSharp.SqlTrellis.Schema.MultiPartName {
private global::DripSharp.SqlTrellis.Schema.Table table = null!;

private string columnName = null!;

private string commentText = null!;

private global::DripSharp.SqlTrellis.Expression.ArrayConstructor arrayConstructor = null!;

private string tableDelimiter = ".";

public Column() {}

public Column(global::DripSharp.SqlTrellis.Schema.Table table, string columnName) {
this.setTable(table);
this.setColumnName(columnName);
}

public Column(global::System.Collections.Generic.IList<string> nameParts) : this(nameParts, ((global::DripSharp.Runtime.JavaCompat.CollectionCount(nameParts) > 1) ? global::DripSharp.Runtime.JavaCompat.NCopies((global::DripSharp.Runtime.JavaCompat.CollectionCount(nameParts) - 1), ".") : (global::System.Collections.Generic.IList<string>)(new global::System.Collections.Generic.List<string>()))) {

}

public Column(global::System.Collections.Generic.IList<string> nameParts, global::System.Collections.Generic.IList<string> delimiters) : this(((global::DripSharp.Runtime.JavaCompat.CollectionCount(nameParts) > 1) ? new global::DripSharp.SqlTrellis.Schema.Table(global::DripSharp.Runtime.JavaCompat.SubList(nameParts, 0, (global::DripSharp.Runtime.JavaCompat.CollectionCount(nameParts) - 1)), global::DripSharp.Runtime.JavaCompat.SubList(delimiters, 0, (global::DripSharp.Runtime.JavaCompat.CollectionCount(delimiters) - 1))) : (global::DripSharp.SqlTrellis.Schema.Table)(default!)), global::DripSharp.Runtime.JavaCompat.ListGet(nameParts, (global::DripSharp.Runtime.JavaCompat.CollectionCount(nameParts) - 1))) {
this.setTableDelimiter((global::DripSharp.Runtime.JavaCompat.ListIsEmpty(delimiters) ? "." : global::DripSharp.Runtime.JavaCompat.ListGet(delimiters, (global::DripSharp.Runtime.JavaCompat.CollectionCount(delimiters) - 1))));
}

public Column(string columnName) : this((global::DripSharp.SqlTrellis.Schema.Table)default!, columnName) {

}

public virtual global::DripSharp.SqlTrellis.Expression.ArrayConstructor getArrayConstructor() {
return this.arrayConstructor;
}

public virtual global::DripSharp.SqlTrellis.Schema.Column setArrayConstructor(global::DripSharp.SqlTrellis.Expression.ArrayConstructor arrayConstructor) {
this.arrayConstructor = arrayConstructor;
return this;
}

public virtual global::DripSharp.SqlTrellis.Schema.Table getTable() {
return this.table;
}

public virtual string getTableName() {
return ((this.table != default!) ? this.table.getName() : (string)(default!));
}

public virtual string getUnquotedTableName() {
return ((this.table != default!) ? this.table.getUnquotedName() : (string)(default!));
}

public virtual string getSchemaName() {
return ((this.table != default!) ? this.table.getSchemaName() : (string)(default!));
}

public virtual string getUnquotedSchemaName() {
return ((this.table != default!) ? this.table.getUnquotedSchemaName() : (string)(default!));
}

public virtual string getCatalogName() {
return ((this.table != default!) ? this.table.getCatalogName() : (string)(default!));
}

public virtual string getUnquotedCatalogName() {
return ((this.table != default!) ? this.table.getUnquotedCatalogName() : (string)(default!));
}

public virtual void setTable(global::DripSharp.SqlTrellis.Schema.Table table) {
this.table = table;
}

public virtual string getColumnName() {
return this.columnName;
}

public virtual string getUnquotedColumnName() {
return global::DripSharp.SqlTrellis.Schema.MultiPartNameStatics.unquote(this.columnName);
}

public virtual void setColumnName(string @string) {
this.columnName = @string;
}

public virtual string getTableDelimiter() {
return this.tableDelimiter;
}

public virtual void setTableDelimiter(string tableDelimiter) {
this.tableDelimiter = tableDelimiter;
}

public virtual string getFullyQualifiedName() {
return this.getFullyQualifiedName(false);
}

public virtual string getUnquotedName() {
return global::DripSharp.SqlTrellis.Schema.MultiPartNameStatics.unquote(this.columnName);
}

public virtual string getFullyQualifiedName(bool aliases) {
global::System.Text.StringBuilder fqn = new global::System.Text.StringBuilder();
if ((this.table != default!)) {
if (((this.table.getAlias() != default!) && aliases)) {
fqn.Append(this.table.getAlias().getName());
} else {
fqn.Append(this.table.getFullyQualifiedName());
}
}
if ((fqn.Length > 0)) {
fqn.Append(this.tableDelimiter);
}
if ((this.columnName != default!)) {
fqn.Append(this.columnName);
}
if ((this.commentText != default!)) {
fqn.Append(" COMMENT ");
fqn.Append(this.commentText);
}
if ((this.arrayConstructor != default!)) {
fqn.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(this.arrayConstructor));
}
return fqn.ToString();
}

public virtual string getName(bool aliases) {
return this.columnName;
}

public virtual T accept<T, S>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor, S context) {
return expressionVisitor.visit(this, context);
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(this.getFullyQualifiedName(true), ((this.commentText != default!) ? global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(" /* ", this.commentText), "*/ ") : ""));
}

public virtual global::DripSharp.SqlTrellis.Schema.Column withTable(global::DripSharp.SqlTrellis.Schema.Table table) {
this.setTable(table);
return this;
}

public virtual global::DripSharp.SqlTrellis.Schema.Column withColumnName(string columnName) {
this.setColumnName(columnName);
return this;
}

public virtual global::DripSharp.SqlTrellis.Schema.Column withCommentText(string commentText) {
this.setCommentText(commentText);
return this;
}

public virtual global::DripSharp.SqlTrellis.Schema.Column withTableDelimiter(string delimiter) {
this.setTableDelimiter(delimiter);
return this;
}

public virtual string getCommentText() {
return this.commentText;
}

public virtual void setCommentText(string commentText) {
this.commentText = commentText;
}

public virtual void accept<T>(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T> expressionVisitor) {
this.accept<T, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<T>)(expressionVisitor), (object)default!);
}
}
