// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/schema/Database.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Schema;

public sealed class Database : global::DripSharp.SqlTrellis.Schema.MultiPartName {
private global::DripSharp.SqlTrellis.Schema.Server server = null!;

private string databaseName = null!;

public Database(string databaseName) {
this.setDatabaseName(databaseName);
}

public Database(global::DripSharp.SqlTrellis.Schema.Server server, string databaseName) {
this.setServer(server);
this.setDatabaseName(databaseName);
}

public global::DripSharp.SqlTrellis.Schema.Server getServer() {
return this.server;
}

public void setServer(global::DripSharp.SqlTrellis.Schema.Server server) {
this.server = server;
}

public string getDatabaseName() {
return this.databaseName;
}

public void setDatabaseName(string databaseName) {
this.databaseName = databaseName;
}

public string getFullyQualifiedName() {
string fqn = "";
if ((this.server != default!)) {
fqn += this.server.getFullyQualifiedName();
}
if (!((fqn.Length == 0))) {
fqn += ".";
}
if ((this.databaseName != default!)) {
fqn += this.databaseName;
}
return fqn;
}

public string getUnquotedName() {
return global::DripSharp.SqlTrellis.Schema.MultiPartName.unquote(this.databaseName);
}

public override string ToString() {
return this.getFullyQualifiedName();
}

public global::DripSharp.SqlTrellis.Schema.Database withServer(global::DripSharp.SqlTrellis.Schema.Server server) {
this.setServer(server);
return this;
}

public global::DripSharp.SqlTrellis.Schema.Database withDatabaseName(string databaseName) {
this.setDatabaseName(databaseName);
return this;
}
}
