// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/schema/Server.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Schema;

public sealed class Server : global::DripSharp.SqlTrellis.Schema.MultiPartName {
public static readonly global::System.Text.RegularExpressions.Regex SERVER_PATTERN = global::DripSharp.Runtime.JavaCompat.CompileRegex("\\[([^\\]]+?)(?:\\\\([^\\]]+))?\\]");

private string serverName = null!;

private string instanceName = null!;

private string simpleName = null!;

public Server(string serverAndInstanceName) {
if ((serverAndInstanceName != default!)) {
global::DripSharp.Runtime.JavaRegexMatcher matcher = global::DripSharp.Runtime.JavaCompat.RegexMatcher(global::DripSharp.SqlTrellis.Schema.Server.SERVER_PATTERN, serverAndInstanceName);
if (!(matcher.Find())) {
this.simpleName = serverAndInstanceName;
} else {
this.setServerName(matcher.Group(1));
this.setInstanceName(matcher.Group(2));
}
}
}

public Server(string serverName, string instanceName) {
this.setServerName(serverName);
this.setInstanceName(instanceName);
}

public string getServerName() {
return this.serverName;
}

public void setServerName(string serverName) {
this.serverName = serverName;
}

public string getInstanceName() {
return this.instanceName;
}

public void setInstanceName(string instanceName) {
this.instanceName = instanceName;
}

public string getFullyQualifiedName() {
if (((((this.serverName != default!) && !((this.serverName.Length == 0))) && (this.instanceName != default!)) && !((this.instanceName.Length == 0)))) {
return global::DripSharp.Runtime.JavaCompat.JavaStringFormat("[%s\\%s]", this.serverName, this.instanceName);
} else {
if (((this.serverName != default!) && !((this.serverName.Length == 0)))) {
return global::DripSharp.Runtime.JavaCompat.JavaStringFormat("[%s]", this.serverName);
} else {
if (((this.simpleName != default!) && !((this.simpleName.Length == 0)))) {
return this.simpleName;
} else {
return "";
}
}
}
}

public string getUnquotedName() {
return global::DripSharp.SqlTrellis.Schema.MultiPartName.unquote(this.serverName);
}

public override string ToString() {
return this.getFullyQualifiedName();
}

public global::DripSharp.SqlTrellis.Schema.Server withServerName(string serverName) {
this.setServerName(serverName);
return this;
}

public global::DripSharp.SqlTrellis.Schema.Server withInstanceName(string instanceName) {
this.setInstanceName(instanceName);
return this;
}
}
