// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/schema/Synonym.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Schema;

public class Synonym : global::DripSharp.SqlTrellis.Parser.ASTNodeAccessImpl, global::DripSharp.SqlTrellis.Schema.MultiPartName {
private const int NAME_IDX = 0;

private const int SCHEMA_IDX = 1;

private const int DATABASE_IDX = 2;

private const int SERVER_IDX = 3;

private global::System.Collections.Generic.IList<string> partItems = new global::System.Collections.Generic.List<string>();

public Synonym() {}

public Synonym(global::System.Collections.Generic.IList<string> partItems) {
this.partItems = new global::System.Collections.Generic.List<string>(partItems);
global::DripSharp.Runtime.JavaCompat.Reverse(this.partItems);
}

public virtual global::DripSharp.SqlTrellis.Schema.Database getDatabase() {
return new global::DripSharp.SqlTrellis.Schema.Database(this.getIndex(global::DripSharp.SqlTrellis.Schema.Synonym.DATABASE_IDX));
}

public virtual void setDatabase(global::DripSharp.SqlTrellis.Schema.Database database) {
this.setIndex(global::DripSharp.SqlTrellis.Schema.Synonym.DATABASE_IDX, database.getDatabaseName());
if ((database.getServer() != default!)) {
this.setIndex(global::DripSharp.SqlTrellis.Schema.Synonym.SERVER_IDX, database.getServer().getFullyQualifiedName());
}
}

public virtual global::DripSharp.SqlTrellis.Schema.Synonym withDatabase(global::DripSharp.SqlTrellis.Schema.Database database) {
this.setDatabase(database);
return this;
}

public virtual string getSchemaName() {
return this.getIndex(global::DripSharp.SqlTrellis.Schema.Synonym.SCHEMA_IDX);
}

public virtual void setSchemaName(string @string) {
this.setIndex(global::DripSharp.SqlTrellis.Schema.Synonym.SCHEMA_IDX, @string);
}

public virtual global::DripSharp.SqlTrellis.Schema.Synonym withSchemaName(string @string) {
this.setSchemaName(@string);
return this;
}

public virtual string getName() {
return this.getIndex(global::DripSharp.SqlTrellis.Schema.Synonym.NAME_IDX);
}

public virtual void setName(string @string) {
this.setIndex(global::DripSharp.SqlTrellis.Schema.Synonym.NAME_IDX, @string);
}

public virtual global::DripSharp.SqlTrellis.Schema.Synonym withName(string @string) {
this.setName(@string);
return this;
}

private void setIndex(int idx, string value) {
int size = global::DripSharp.Runtime.JavaCompat.CollectionCount(this.partItems);
for (int i = 0; (i < ((idx - size) + 1)); i++) {
global::DripSharp.Runtime.JavaCompat.Add(this.partItems, default!);
}
global::DripSharp.Runtime.JavaCompat.ListSet(this.partItems, idx, value);
}

private string getIndex(int idx) {
if ((idx < global::DripSharp.Runtime.JavaCompat.CollectionCount(this.partItems))) {
return global::DripSharp.Runtime.JavaCompat.ListGet(this.partItems, idx);
} else {
return default!;
}
}

public virtual string getFullyQualifiedName() {
global::System.Text.StringBuilder fqn = new global::System.Text.StringBuilder();
for (int i = (global::DripSharp.Runtime.JavaCompat.CollectionCount(this.partItems) - 1); (i >= 0); i--) {
string part = global::DripSharp.Runtime.JavaCompat.ListGet(this.partItems, i);
if ((part == default!)) {
part = "";
}
fqn.Append(part);
if ((i != 0)) {
fqn.Append(".");
}
}
return fqn.ToString();
}

public virtual string getUnquotedName() {
return global::DripSharp.SqlTrellis.Schema.MultiPartName.unquote(global::DripSharp.Runtime.JavaCompat.ListGet(this.partItems, global::DripSharp.SqlTrellis.Schema.Synonym.NAME_IDX));
}

public override string ToString() {
global::System.Text.StringBuilder sql = new global::System.Text.StringBuilder(this.getFullyQualifiedName());
return sql.ToString();
}
}
