// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/ConnectExpressionsVisitor.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util;

public abstract class ConnectExpressionsVisitor<T> : global::DripSharp.SqlTrellis.Statement.Select.SelectItemVisitor<T>, global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T> {
private readonly global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>> itemsExpr = new global::System.Collections.Generic.List<global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>>();

private string alias = "expr";

public ConnectExpressionsVisitor() {}

public ConnectExpressionsVisitor(string alias) {
this.alias = alias;
}

protected internal abstract global::DripSharp.SqlTrellis.Expression.BinaryExpression createBinaryExpression();

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect parenthesedSelect, S context) {
parenthesedSelect.getSelect().accept((global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T>)(this), context);
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.LateralSubSelect lateralSubSelect, S context) {
lateralSubSelect.getSelect().accept((global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T>)(this), context);
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect, S context) {
foreach (var item in plainSelect.getSelectItems()) {
item.accept<T, S>((global::DripSharp.SqlTrellis.Statement.Select.SelectItemVisitor<T>)(this), context);
}
if ((global::DripSharp.Runtime.JavaCompat.CollectionCount(this.itemsExpr) > 1)) {
global::DripSharp.SqlTrellis.Expression.BinaryExpression binExpr = this.createBinaryExpression();
binExpr.setLeftExpression(global::DripSharp.Runtime.JavaCompat.ListGet(this.itemsExpr, 0).getExpression());
for (int i = 1; (i < (global::DripSharp.Runtime.JavaCompat.CollectionCount(this.itemsExpr) - 1)); i++) {
binExpr.setRightExpression(global::DripSharp.Runtime.JavaCompat.ListGet(this.itemsExpr, i).getExpression());
global::DripSharp.SqlTrellis.Expression.BinaryExpression binExpr2 = this.createBinaryExpression();
binExpr2.setLeftExpression(binExpr);
binExpr = binExpr2;
}
binExpr.setRightExpression(global::DripSharp.Runtime.JavaCompat.ListGet(this.itemsExpr, (global::DripSharp.Runtime.JavaCompat.CollectionCount(this.itemsExpr) - 1)).getExpression());
global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression> sei = new global::DripSharp.SqlTrellis.Statement.Select.SelectItem<global::DripSharp.SqlTrellis.Expression.Expression>();
sei.setExpression(binExpr);
(plainSelect.getSelectItems()).Clear();
global::DripSharp.Runtime.JavaCompat.Add(plainSelect.getSelectItems(), sei);
}
global::DripSharp.Runtime.JavaCompat.ListGet(plainSelect.getSelectItems(), 0).setAlias(new global::DripSharp.SqlTrellis.Expression.Alias(this.alias));
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Piped.FromQuery fromQuery, S context) {
throw new global::System.NotSupportedException("Not supported yet.");
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList setOpList, S context) {
foreach (global::DripSharp.SqlTrellis.Statement.Select.Select select in setOpList.getSelects()) {
select.accept((global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<T>)(this), context);
}
return default!;
}

public virtual T visit<S, TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.WithItem<TWildcard0_0> withItem, S context) where TWildcard0_0 : global::DripSharp.SqlTrellis.Statement.ParenthesedStatement {
return default!;
}

public virtual T visit<S, TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.SelectItem<TWildcard0_0> selectItem, S context) where TWildcard0_0 : global::DripSharp.SqlTrellis.Expression.Expression {
global::DripSharp.Runtime.JavaCompat.Add(this.itemsExpr, selectItem);
return default!;
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.Values aThis, S context) {
throw new global::System.NotSupportedException("Not supported yet.");
}

public virtual T visit<S>(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement, S context) {
throw new global::System.NotSupportedException("Not supported yet.");
}
}
