// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/allowedtypes/AllowedTypesValidation.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Allowedtypes;

public class AllowedTypesValidation : global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability {
public const string NAME = "allowed types";

public virtual void validate(global::DripSharp.SqlTrellis.Util.Validation.ValidationContext context, global::System.Action<global::DripSharp.SqlTrellis.Util.Validation.ValidationException> errorConsumer) {
object arg = context.getOptional<object>(global::DripSharp.SqlTrellis.Util.Validation.Allowedtypes.AllowedTypesContext.argument, typeof(object));
bool? allowNull = context.getOptional<bool>(global::DripSharp.SqlTrellis.Util.Validation.Allowedtypes.AllowedTypesContext.allow_null, typeof(bool));
global::System.Collections.Generic.ICollection<global::System.Type> allowedTypes = global::DripSharp.Runtime.JavaCompat.CastCollection<global::System.Type>(context.get<global::System.Collections.ICollection>(global::DripSharp.SqlTrellis.Util.Validation.Allowedtypes.AllowedTypesContext.allowed_types, typeof(global::System.Collections.ICollection)));
if ((arg != default!)) {
bool error = true;
foreach (global::System.Type cls in allowedTypes) {
if (cls.IsAssignableFrom(((object)(arg)).GetType())) {
error = false;
break;
}
}
if (error) {
errorConsumer(((global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability)(this)).toError(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(((object)(arg)).GetType(), " is not a valid argument - expected one of "), allowedTypes)));
}
} else {
if (global::DripSharp.Runtime.JavaCompat.Equals(false, allowNull)) {
errorConsumer(((global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability)(this)).toError(global::DripSharp.Runtime.JavaCompat.Concat("argument is missing one of ", allowedTypes)));
}
}
}

public virtual string getName() {
return global::DripSharp.SqlTrellis.Util.Validation.Allowedtypes.AllowedTypesValidation.NAME;
}
}
