// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/deparser/CreateTableDeParser.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Deparser;

public class CreateTableDeParser : global::DripSharp.SqlTrellis.Util.Deparser.AbstractDeParser<global::DripSharp.SqlTrellis.Statement.Create.Table.CreateTable> {
private global::DripSharp.SqlTrellis.Util.Deparser.StatementDeParser statementDeParser = null!;

public CreateTableDeParser(global::System.Text.StringBuilder buffer) : base(buffer) {

}

public CreateTableDeParser(global::DripSharp.SqlTrellis.Util.Deparser.StatementDeParser statementDeParser, global::System.Text.StringBuilder buffer) : base(buffer) {
this.statementDeParser = statementDeParser;
}

public override void deParse(global::DripSharp.SqlTrellis.Statement.Create.Table.CreateTable createTable) {
base.builder.Append("CREATE ");
if (createTable.isOrReplace()) {
base.builder.Append("OR REPLACE ");
}
if (createTable.isUnlogged()) {
base.builder.Append("UNLOGGED ");
}
string @params = global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(createTable.getCreateOptionsStrings()), false, false);
if (!((@params.Length == 0))) {
base.builder.Append(@params).Append(' ');
}
base.builder.Append("TABLE ");
if (createTable.isIfNotExists()) {
base.builder.Append("IF NOT EXISTS ");
}
base.builder.Append(createTable.getTable().getFullyQualifiedName());
if (((createTable.getColumns() != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(createTable.getColumns())))) {
base.builder.Append(" (");
global::DripSharp.Runtime.JavaIterator<string> columnIterator = global::DripSharp.Runtime.JavaCompat.Iterator(createTable.getColumns());
base.builder.Append(columnIterator.Next()!);
while (columnIterator.HasNext()) {
base.builder.Append(", ").Append(columnIterator.Next()!);
}
base.builder.Append(")");
}
if ((createTable.getColumnDefinitions() != default!)) {
base.builder.Append(" (");
for (global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Statement.Create.Table.ColumnDefinition> iter = global::DripSharp.Runtime.JavaCompat.Iterator(createTable.getColumnDefinitions()); iter.HasNext(); ) {
global::DripSharp.SqlTrellis.Statement.Create.Table.ColumnDefinition columnDefinition = iter.Next()!;
base.builder.Append(columnDefinition.getColumnName());
base.builder.Append(" ");
base.builder.Append(columnDefinition.getColDataType().ToString());
if ((columnDefinition.getColumnSpecs() != default!)) {
foreach (string s in columnDefinition.getColumnSpecs()) {
base.builder.Append(" ");
base.builder.Append(s);
}
}
if (iter.HasNext()) {
base.builder.Append(", ");
}
}
if ((createTable.getIndexes() != default!)) {
foreach (global::DripSharp.SqlTrellis.Statement.Create.Table.Index index in createTable.getIndexes()) {
base.builder.Append(", ");
base.builder.Append(index.ToString());
}
}
base.builder.Append(")");
}
@params = global::DripSharp.SqlTrellis.Statement.Select.Select.getStringList(global::DripSharp.Runtime.JavaCompat.CastObjects(createTable.getTableOptionsStrings()), false, false);
if (!(global::DripSharp.Runtime.JavaCompat.Equals("", @params))) {
base.builder.Append(' ').Append(@params);
}
if ((createTable.getRowMovement() != default!)) {
base.builder.Append(' ').Append(createTable.getRowMovement().getMode().ToString()).Append(" ROW MOVEMENT");
}
if ((createTable.getSelect() != default!)) {
base.builder.Append(" AS ");
if (createTable.isSelectParenthesis()) {
base.builder.Append("(");
}
global::DripSharp.SqlTrellis.Statement.Select.Select sel = createTable.getSelect();
sel.accept<global::System.Text.StringBuilder, object>((global::DripSharp.SqlTrellis.Statement.StatementVisitor<global::System.Text.StringBuilder>)(this.statementDeParser), (object)default!);
if (createTable.isSelectParenthesis()) {
base.builder.Append(")");
}
}
if ((createTable.getLikeTable() != default!)) {
base.builder.Append(" LIKE ");
if (createTable.isSelectParenthesis()) {
base.builder.Append("(");
}
global::DripSharp.SqlTrellis.Schema.Table table = createTable.getLikeTable();
base.builder.Append(table.getFullyQualifiedName());
if (createTable.isSelectParenthesis()) {
base.builder.Append(")");
}
}
if ((createTable.getSpannerInterleaveIn() != default!)) {
base.builder.Append(", ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(createTable.getSpannerInterleaveIn()));
}
}
}
