// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/deparser/DeleteDeParser.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Deparser;

public class DeleteDeParser : global::DripSharp.SqlTrellis.Util.Deparser.AbstractDeParser<global::DripSharp.SqlTrellis.Statement.Delete.Delete> {
private global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder> expressionVisitor = new global::DripSharp.SqlTrellis.Expression.ExpressionVisitorAdapter<global::System.Text.StringBuilder>();

public DeleteDeParser() : base(new global::System.Text.StringBuilder()) {

}

public DeleteDeParser(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder> expressionVisitor, global::System.Text.StringBuilder buffer) : base(buffer) {
this.expressionVisitor = expressionVisitor;
}

public override void deParse(global::DripSharp.SqlTrellis.Statement.Delete.Delete delete) {
if (((delete.getWithItemsList() != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(delete.getWithItemsList())))) {
base.builder.Append("WITH ");
for (global::DripSharp.Runtime.JavaIterator<global::DripSharp.SqlTrellis.Statement.Select.WithItem<global::DripSharp.SqlTrellis.Statement.ParenthesedStatement>> iter = global::DripSharp.Runtime.JavaCompat.Iterator(delete.getWithItemsList()); iter.HasNext(); ) {
var withItem = iter.Next()!;
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(withItem));
if (iter.HasNext()) {
base.builder.Append(",");
}
base.builder.Append(" ");
}
}
base.builder.Append("DELETE");
if ((delete.getOracleHint() != default!)) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(delete.getOracleHint())).Append(" ");
}
if ((delete.getModifierPriority() != default!)) {
base.builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(delete.getModifierPriority()));
}
if (delete.isModifierQuick()) {
base.builder.Append(" QUICK");
}
if (delete.isModifierIgnore()) {
base.builder.Append(" IGNORE");
}
if (((delete.getTables() != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(delete.getTables())))) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(delete.getTables()), (value0) => value0.getFullyQualifiedName()), global::DripSharp.Runtime.JavaCompat.Joining(", ", " ", "")));
}
if ((delete.getOutputClause() != default!)) {
delete.getOutputClause().appendTo(base.builder);
}
if (delete.isHasFrom()) {
base.builder.Append(" FROM");
}
base.builder.Append(" ").Append(delete.getTable().ToString());
if (((delete.getUsingList() != default!) && !(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(delete.getUsingList())))) {
base.builder.Append(" USING").Append(global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(delete.getUsingList()), (value0) => value0.ToString()), global::DripSharp.Runtime.JavaCompat.Joining(", ", " ", "")));
}
if ((delete.getJoins() != default!)) {
foreach (global::DripSharp.SqlTrellis.Statement.Select.Join join in delete.getJoins()) {
if (join.isSimple()) {
base.builder.Append(", ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(join));
} else {
base.builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(join));
}
}
}
this.deparseWhereClause(delete);
if ((delete.getPreferringClause() != default!)) {
base.builder.Append(" ").Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(delete.getPreferringClause()));
}
if ((delete.getOrderByElements() != default!)) {
new global::DripSharp.SqlTrellis.Util.Deparser.OrderByDeParser(this.expressionVisitor, base.builder).deParse(delete.getOrderByElements());
}
if ((delete.getLimit() != default!)) {
new global::DripSharp.SqlTrellis.Util.Deparser.LimitDeparser(this.expressionVisitor, base.builder).deParse(delete.getLimit());
}
if ((delete.getReturningClause() != default!)) {
delete.getReturningClause().appendTo(base.builder);
}
}

protected internal virtual void deparseWhereClause(global::DripSharp.SqlTrellis.Statement.Delete.Delete delete) {
if ((delete.getWhere() != default!)) {
base.builder.Append(" WHERE ");
delete.getWhere().accept<global::System.Text.StringBuilder, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder>)(this.expressionVisitor), (object)default!);
}
}

public virtual global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder> getExpressionVisitor() {
return this.expressionVisitor;
}

public virtual void setExpressionVisitor(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder> visitor) {
this.expressionVisitor = visitor;
}
}
