// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/deparser/ShowStatementDeParser.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Deparser;

public class ShowStatementDeParser : global::DripSharp.SqlTrellis.Util.Deparser.AbstractDeParser<global::DripSharp.SqlTrellis.Statement.ShowStatement> {
public ShowStatementDeParser(global::System.Text.StringBuilder buffer) : base(buffer) {

}

public override void deParse(global::DripSharp.SqlTrellis.Statement.ShowStatement show) {
base.builder.Append("SHOW ").Append(show.getName());
}
}
