// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/deparser/TableStatementDeParser.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Deparser;

public class TableStatementDeParser : global::DripSharp.SqlTrellis.Util.Deparser.AbstractDeParser<global::DripSharp.SqlTrellis.Statement.Select.TableStatement>, global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<global::System.Text.StringBuilder> {
private readonly global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder> expressionVisitor = null!;

public TableStatementDeParser(global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder> expressionVisitor, global::System.Text.StringBuilder buffer) : base(buffer) {
this.expressionVisitor = expressionVisitor;
}

public override void deParse(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement) {
tableStatement.accept<global::System.Text.StringBuilder, object>((global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<global::System.Text.StringBuilder>)(this), (object)default!);
}

public virtual void deparse(global::DripSharp.SqlTrellis.Statement.Select.Offset offset) {
base.builder.Append(" OFFSET ");
offset.getOffset().accept<global::System.Text.StringBuilder, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<global::System.Text.StringBuilder>)(this.expressionVisitor), (object)default!);
if ((offset.getOffsetParam() != default!)) {
base.builder.Append(" ").Append(offset.getOffsetParam());
}
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect parenthesedSelect, S context) {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect, S context) {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Piped.FromQuery fromQuery, S context) {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList setOperationList, S context) {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S, TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.WithItem<TWildcard0_0> withItem, S context) where TWildcard0_0 : global::DripSharp.SqlTrellis.Statement.ParenthesedStatement {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Select.Values values, S context) {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Select.LateralSubSelect lateralSubSelect, S context) {
return base.builder;
}

public virtual global::System.Text.StringBuilder visit<S>(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement, S context) {
base.builder.Append("TABLE ");
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(tableStatement.getTable()));
if ((tableStatement.getOrderByElements() != default!)) {
new global::DripSharp.SqlTrellis.Util.Deparser.OrderByDeParser(this.expressionVisitor, base.builder).deParse(tableStatement.getOrderByElements());
}
if ((tableStatement.getLimit() != default!)) {
new global::DripSharp.SqlTrellis.Util.Deparser.LimitDeparser(this.expressionVisitor, base.builder).deParse(tableStatement.getLimit());
}
if ((tableStatement.getOffset() != default!)) {
this.deparse(tableStatement.getOffset());
}
((global::DripSharp.SqlTrellis.Statement.Select.FromItem)(tableStatement)).appendTo(base.builder, tableStatement.getAlias(), (global::DripSharp.SqlTrellis.Statement.Select.SampleClause)default!, tableStatement.getPivot(), tableStatement.getUnPivot());
return base.builder;
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.LateralSubSelect lateralSubSelect) {
this.visit<object>(lateralSubSelect, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect parenthesedSelect) {
this.visit<object>(parenthesedSelect, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect) {
this.visit<object>(plainSelect, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.SetOperationList setOpList) {
this.visit<object>(setOpList, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.TableStatement tableStatement) {
this.visit<object>(tableStatement, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.Values values) {
this.visit<object>(values, (object)default!);
}

public virtual void visit<TWildcard0_0>(global::DripSharp.SqlTrellis.Statement.Select.WithItem<TWildcard0_0> withItem) where TWildcard0_0 : global::DripSharp.SqlTrellis.Statement.ParenthesedStatement {
this.visit<object, TWildcard0_0>(withItem, (object)default!);
}
}
