// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Validator;

public class ExpressionValidator : global::DripSharp.SqlTrellis.Util.Validation.Validator.AbstractValidator<global::DripSharp.SqlTrellis.Expression.Expression>, global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object> {
public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Addition addition, S context) {
this.visitBinaryExpression(addition, " + ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.AndExpression andExpression, S context) {
this.visitBinaryExpression(andExpression, (andExpression.isUseOperator() ? " && " : " AND "));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Between between, S context) {
between.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
between.getBetweenExpressionStart().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
between.getBetweenExpressionEnd().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.OverlapsCondition overlapsCondition, S context) {
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(overlapsCondition.getLeft()));
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(overlapsCondition.getRight()));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.EqualsTo equalsTo, S context) {
this.validateOldOracleJoinBinaryExpression(equalsTo, " = ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Division division, S context) {
this.visitBinaryExpression(division, " / ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.IntegerDivision division, S context) {
this.visitBinaryExpression(division, " DIV ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.DoubleValue doubleValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.HexValue hexValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.NotExpression notExpr, S context) {
notExpr.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseRightShift expr, S context) {
this.visitBinaryExpression(expr, " >> ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseLeftShift expr, S context) {
this.visitBinaryExpression(expr, " << ");
return default!;
}

public virtual void validateOldOracleJoinBinaryExpression<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.OldOracleJoinBinaryExpression expression, string @operator, S context) {
foreach (global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability c in this.getCapabilities()) {
this.validateOptionalExpression(expression.getLeftExpression(), this);
if ((expression.getOldOracleJoinSyntax() != global::DripSharp.SqlTrellis.Expression.Operators.Relational.SupportsOldOracleJoinSyntaxStatics.NO_ORACLE_JOIN)) {
this.validateFeature(c, global::DripSharp.SqlTrellis.Parser.Feature.Feature.oracleOldJoinSyntax);
}
this.validateOptionalExpression(expression.getRightExpression(), this);
if ((expression.getOraclePriorPosition() != global::DripSharp.SqlTrellis.Expression.Operators.Relational.SupportsOldOracleJoinSyntaxStatics.NO_ORACLE_PRIOR)) {
this.validateFeature(c, global::DripSharp.SqlTrellis.Parser.Feature.Feature.oraclePriorPosition);
}
}
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.GreaterThan greaterThan, S context) {
this.validateOldOracleJoinBinaryExpression(greaterThan, " > ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.GreaterThanEquals greaterThanEquals, S context) {
this.validateOldOracleJoinBinaryExpression(greaterThanEquals, " >= ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.InExpression inExpression, S context) {
foreach (global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability c in this.getCapabilities()) {
this.validateOptionalExpression(inExpression.getLeftExpression(), this);
if ((inExpression.getOldOracleJoinSyntax() != global::DripSharp.SqlTrellis.Expression.Operators.Relational.SupportsOldOracleJoinSyntaxStatics.NO_ORACLE_JOIN)) {
this.validateFeature(c, global::DripSharp.SqlTrellis.Parser.Feature.Feature.oracleOldJoinSyntax);
}
}
this.validateOptionalExpression(inExpression.getRightExpression(), this);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IncludesExpression includesExpression, S context) {
this.validateOptionalExpression(includesExpression.getLeftExpression(), this);
this.validateOptionalExpression(includesExpression.getRightExpression(), this);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExcludesExpression excludesExpression, S context) {
this.validateOptionalExpression(excludesExpression.getLeftExpression(), this);
this.validateOptionalExpression(excludesExpression.getRightExpression(), this);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch fullTextSearch, S context) {
this.validateOptionalExpressions(fullTextSearch.getMatchColumns());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.SignedExpression signedExpression, S context) {
signedExpression.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsNullExpression isNullExpression, S context) {
isNullExpression.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsBooleanExpression isBooleanExpression, S context) {
isBooleanExpression.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsUnknownExpression isUnknownExpression, S context) {
isUnknownExpression.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.JdbcParameter jdbcParameter, S context) {
this.validateFeature(global::DripSharp.SqlTrellis.Parser.Feature.Feature.jdbcParameter);
return default!;
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.PlainSelect plainSelect) {
this.visit<object>(plainSelect, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Addition addition) {
this.visit<object>(addition, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.AndExpression andExpression) {
this.visit<object>(andExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Between between) {
this.visit<object>(between, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.OverlapsCondition overlapsCondition) {
this.visit<object>(overlapsCondition, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.EqualsTo equalsTo) {
this.visit<object>(equalsTo, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Division division) {
this.visit<object>(division, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.IntegerDivision division) {
this.visit<object>(division, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.DoubleValue doubleValue) {
this.visit<object>(doubleValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.HexValue hexValue) {
this.visit<object>(hexValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.NotExpression notExpr) {
this.visit<object>(notExpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseRightShift expr) {
this.visit<object>(expr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseLeftShift expr) {
this.visit<object>(expr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.GreaterThan greaterThan) {
this.visit<object>(greaterThan, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.GreaterThanEquals greaterThanEquals) {
this.visit<object>(greaterThanEquals, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.InExpression inExpression) {
this.visit<object>(inExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IncludesExpression includesExpression) {
this.visit<object>(includesExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExcludesExpression excludesExpression) {
this.visit<object>(excludesExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.FullTextSearch fullTextSearch) {
this.visit<object>(fullTextSearch, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.SignedExpression signedExpression) {
this.visit<object>(signedExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsNullExpression isNullExpression) {
this.visit<object>(isNullExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsBooleanExpression isBooleanExpression) {
this.visit<object>(isBooleanExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsUnknownExpression isUnknownExpression) {
this.visit<object>(isUnknownExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.JdbcParameter jdbcParameter) {
this.visit<object>(jdbcParameter, (object)default!);
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.LikeExpression likeExpression, S context) {
this.validateFeature(global::DripSharp.SqlTrellis.Parser.Feature.Feature.exprLike);
this.visitBinaryExpression(likeExpression, global::DripSharp.Runtime.JavaCompat.Concat((likeExpression.isNot() ? " NOT" : ""), (likeExpression.isCaseInsensitive() ? " ILIKE " : " LIKE ")));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExistsExpression existsExpression, S context) {
existsExpression.getRightExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.MemberOfExpression memberOfExpression, S context) {
memberOfExpression.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
memberOfExpression.getRightExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.LongValue longValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.MinorThan minorThan, S context) {
this.validateOldOracleJoinBinaryExpression(minorThan, " < ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.MinorThanEquals minorThanEquals, S context) {
this.validateOldOracleJoinBinaryExpression(minorThanEquals, " <= ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Multiplication multiplication, S context) {
this.visitBinaryExpression(multiplication, " * ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.NotEqualsTo notEqualsTo, S context) {
this.validateOldOracleJoinBinaryExpression(notEqualsTo, global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(" ", notEqualsTo.getStringExpression()), " "), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.DoubleAnd doubleAnd, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Contains contains, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ContainedBy containedBy, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.NullValue nullValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.OrExpression orExpression, S context) {
this.visitBinaryExpression(orExpression, " OR ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.XorExpression xorExpression, S context) {
this.visitBinaryExpression(xorExpression, " XOR ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.StringValue stringValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.BooleanValue booleanValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Subtraction subtraction, S context) {
this.visitBinaryExpression(subtraction, " - ");
return default!;
}

protected internal virtual void visitBinaryExpression(global::DripSharp.SqlTrellis.Expression.BinaryExpression binaryExpression, string @operator) {
binaryExpression.getLeftExpression().accept<object, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), (object)default!);
binaryExpression.getRightExpression().accept<object, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), (object)default!);
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect selectBody, S context) {
this.validateOptionalFromItem(selectBody);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Schema.Column tableColumn, S context) {
this.validateName(global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject.column, tableColumn.getFullyQualifiedName());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Function function, S context) {
this.validateFeature(global::DripSharp.SqlTrellis.Parser.Feature.Feature.function);
this.validateOptionalExpressionList(function.getNamedParameters());
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(function.getParameters()));
object attribute = function.getAttribute();
if ((attribute is global::DripSharp.SqlTrellis.Expression.Expression)) {
this.validateOptionalExpression((global::DripSharp.SqlTrellis.Expression.Expression)(attribute!), this);
}
this.validateOptionalExpression(function.getKeep(), this);
this.validateOptionalOrderByElements(function.getOrderByElements());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.DateValue dateValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.TimestampValue timestampValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.TimeValue timeValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.CaseExpression caseExpression, S context) {
global::DripSharp.SqlTrellis.Expression.Expression switchExp = caseExpression.getSwitchExpression();
if ((switchExp != default!)) {
switchExp.accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
global::DripSharp.Runtime.JavaCompat.ForEach(caseExpression.getWhenClauses(), (wc) => wc.accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context));
global::DripSharp.SqlTrellis.Expression.Expression elseExp = caseExpression.getElseExpression();
if ((elseExp != default!)) {
elseExp.accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
return default!;
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.LikeExpression likeExpression) {
this.visit<object>(likeExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExistsExpression existsExpression) {
this.visit<object>(existsExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.MemberOfExpression memberOfExpression) {
this.visit<object>(memberOfExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.LongValue longValue) {
this.visit<object>(longValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.MinorThan minorThan) {
this.visit<object>(minorThan, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.MinorThanEquals minorThanEquals) {
this.visit<object>(minorThanEquals, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Multiplication multiplication) {
this.visit<object>(multiplication, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.NotEqualsTo notEqualsTo) {
this.visit<object>(notEqualsTo, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.DoubleAnd doubleAnd) {
this.visit<object>(doubleAnd, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Contains contains) {
this.visit<object>(contains, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ContainedBy containedBy) {
this.visit<object>(containedBy, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.NullValue nullValue) {
this.visit<object>(nullValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.OrExpression orExpression) {
this.visit<object>(orExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Conditional.XorExpression xorExpression) {
this.visit<object>(xorExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.StringValue stringValue) {
this.visit<object>(stringValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.BooleanValue booleanValue) {
this.visit<object>(booleanValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Subtraction subtraction) {
this.visit<object>(subtraction, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.ParenthesedSelect selectBody) {
this.visit<object>(selectBody, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Schema.Column tableColumn) {
this.visit<object>(tableColumn, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Function function) {
this.visit<object>(function, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.DateValue dateValue) {
this.visit<object>(dateValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.TimestampValue timestampValue) {
this.visit<object>(timestampValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.TimeValue timeValue) {
this.visit<object>(timeValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.CaseExpression caseExpression) {
this.visit<object>(caseExpression, (object)default!);
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.WhenClause whenClause, S context) {
whenClause.getWhenExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
whenClause.getThenExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.AnyComparisonExpression anyComparisonExpression, S context) {
anyComparisonExpression.getSelect().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Concat concat, S context) {
this.visitBinaryExpression(concat, " || ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Matches matches, S context) {
this.validateOldOracleJoinBinaryExpression(matches, " @@ ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseAnd bitwiseAnd, S context) {
this.visitBinaryExpression(bitwiseAnd, " & ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseOr bitwiseOr, S context) {
this.visitBinaryExpression(bitwiseOr, " | ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseXor bitwiseXor, S context) {
this.visitBinaryExpression(bitwiseXor, " ^ ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.CastExpression cast, S context) {
cast.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Modulo modulo, S context) {
this.visitBinaryExpression(modulo, " % ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.AnalyticExpression aexpr, S context) {
this.validateOptionalExpression(aexpr.getExpression(), this);
this.validateOptionalExpression(aexpr.getOffset(), this);
this.validateOptionalExpression(aexpr.getDefaultValue(), this);
this.validateOptionalExpression(aexpr.getKeep(), this);
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(aexpr.getPartitionExpressionList()));
this.validateOptionalOrderByElements(aexpr.getOrderByElements());
global::DripSharp.SqlTrellis.Expression.WindowElement windowElement = aexpr.getWindowElement();
if ((windowElement != default!)) {
this.validateOptionalWindowOffset(windowElement.getOffset());
global::DripSharp.SqlTrellis.Expression.WindowRange range = windowElement.getRange();
if ((range != default!)) {
this.validateOptionalWindowOffset(range.getStart());
this.validateOptionalWindowOffset(range.getEnd());
}
}
this.validateOptionalExpression(aexpr.getFilterExpression());
return default!;
}

private void validateOptionalWindowOffset(global::DripSharp.SqlTrellis.Expression.WindowOffset offset) {
if ((offset != default!)) {
this.validateOptionalExpression(offset.getExpression());
}
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.ExtractExpression eexpr, S context) {
eexpr.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.IntervalExpression iexpr, S context) {
this.validateOptionalExpression(iexpr.getExpression());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.JdbcNamedParameter jdbcNamedParameter, S context) {
this.validateFeature(global::DripSharp.SqlTrellis.Parser.Feature.Feature.jdbcNamedParameter);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.OracleHierarchicalExpression oexpr, S context) {
this.validateFeature(global::DripSharp.SqlTrellis.Parser.Feature.Feature.oracleHierarchicalExpression);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.RegExpMatchOperator rexpr, S context) {
this.visitBinaryExpression(rexpr, global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(" ", rexpr.getStringExpression()), " "));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.JsonExpression jsonExpr, S context) {
this.validateOptionalExpression(jsonExpr.getExpression());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.JsonOperator jsonExpr, S context) {
this.visitBinaryExpression(jsonExpr, global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(" ", jsonExpr.getStringExpression()), " "));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.UserVariable var, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.NumericBind bind, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.KeepExpression aexpr, S context) {
this.validateOptionalOrderByElements(aexpr.getOrderByElements());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.MySQLGroupConcat groupConcat, S context) {
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(groupConcat.getExpressionList()));
this.validateOptionalOrderByElements(groupConcat.getOrderByElements());
return default!;
}

private void validateOptionalExpressionList(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<global::DripSharp.SqlTrellis.Expression.Expression> expressionList) {
if ((expressionList != default!)) {
foreach (global::DripSharp.SqlTrellis.Expression.Expression expression in expressionList) {
expression.accept<object, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), (object)default!);
}
}
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.WhenClause whenClause) {
this.visit<object>(whenClause, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.AnyComparisonExpression anyComparisonExpression) {
this.visit<object>(anyComparisonExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Concat concat) {
this.visit<object>(concat, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Matches matches) {
this.visit<object>(matches, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseAnd bitwiseAnd) {
this.visit<object>(bitwiseAnd, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseOr bitwiseOr) {
this.visit<object>(bitwiseOr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.BitwiseXor bitwiseXor) {
this.visit<object>(bitwiseXor, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.CastExpression cast) {
this.visit<object>(cast, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Arithmetic.Modulo modulo) {
this.visit<object>(modulo, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.AnalyticExpression aexpr) {
this.visit<object>(aexpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.ExtractExpression eexpr) {
this.visit<object>(eexpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.IntervalExpression iexpr) {
this.visit<object>(iexpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.JdbcNamedParameter jdbcNamedParameter) {
this.visit<object>(jdbcNamedParameter, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.OracleHierarchicalExpression oexpr) {
this.visit<object>(oexpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.RegExpMatchOperator rexpr) {
this.visit<object>(rexpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.JsonExpression jsonExpr) {
this.visit<object>(jsonExpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.JsonOperator jsonExpr) {
this.visit<object>(jsonExpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.UserVariable var) {
this.visit<object>(var, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.NumericBind bind) {
this.visit<object>(bind, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.KeepExpression aexpr) {
this.visit<object>(aexpr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.MySQLGroupConcat groupConcat) {
this.visit<object>(groupConcat, (object)default!);
}

public virtual object visit<S, TWildcard0_0>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<TWildcard0_0> expressionList, S context) where TWildcard0_0 : global::DripSharp.SqlTrellis.Expression.Expression {
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(expressionList));
return default!;
}

public virtual object visit<S, TWildcard0_0>(global::DripSharp.SqlTrellis.Expression.RowConstructor<TWildcard0_0> rowConstructor, S context) where TWildcard0_0 : global::DripSharp.SqlTrellis.Expression.Expression {
this.validateOptionalExpressionList(global::DripSharp.SqlTrellis.SqlTrellisGenericCompatibility.CastExpressionList<global::DripSharp.SqlTrellis.Expression.Expression>(rowConstructor));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.RowGetExpression rowGetExpression, S context) {
rowGetExpression.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.OracleHint hint, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.TimeKeyExpression timeKeyExpression, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.DateTimeLiteralExpression literal, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.NextValExpression nextVal, S context) {
this.validateName(global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject.sequence, nextVal.getName());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.CollateExpression col, S context) {
this.validateOptionalExpression(col.getLeftExpression());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.SimilarToExpression expr, S context) {
this.validateFeature(global::DripSharp.SqlTrellis.Parser.Feature.Feature.exprSimilarTo);
this.visitBinaryExpression(expr, global::DripSharp.Runtime.JavaCompat.Concat((expr.isNot() ? " NOT" : ""), " SIMILAR TO "));
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.ArrayExpression array, S context) {
array.getObjExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
if ((array.getIndexExpression() != default!)) {
array.getIndexExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
if ((array.getStartIndexExpression() != default!)) {
array.getStartIndexExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
if ((array.getStopIndexExpression() != default!)) {
array.getStopIndexExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.ArrayConstructor aThis, S context) {
foreach (global::DripSharp.SqlTrellis.Expression.Expression expression in aThis.getExpressions()) {
expression.accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
return default!;
}

public override void validate(global::DripSharp.SqlTrellis.Expression.Expression expression) {
expression.accept<object, object>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), (object)default!);
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.VariableAssignment a, S context) {
this.validateOptionalExpression(a.getExpression());
if ((a.getVariable() != default!)) {
a.getVariable().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.TimezoneExpression a, S context) {
this.validateOptionalExpression(a.getLeftExpression());
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.XMLSerializeExpr xml, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction expression, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.JsonFunction expression, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.ConnectByRootOperator connectByRootOperator, S context) {
connectByRootOperator.getColumn().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.ConnectByPriorOperator connectByPriorOperator, S context) {
connectByPriorOperator.getColumn().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.OracleNamedFunctionParameter oracleNamedFunctionParameter, S context) {
oracleNamedFunctionParameter.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Statement.Select.AllColumns allColumns, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Statement.Select.AllTableColumns allTableColumns, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Statement.Select.FunctionAllColumns functionColumns, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.AllValue allValue, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsDistinctExpression isDistinctExpression, S context) {
isDistinctExpression.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
isDistinctExpression.getRightExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.GeometryDistance geometryDistance, S context) {
this.validateOldOracleJoinBinaryExpression(geometryDistance, " <-> ", context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Statement.Select.Select select, S context) {
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.TranscodingFunction transcodingFunction, S context) {
transcodingFunction.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.TrimFunction trimFunction, S context) {
if ((trimFunction.getExpression() != default!)) {
trimFunction.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
if ((trimFunction.getFromExpression() != default!)) {
trimFunction.getFromExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.RangeExpression rangeExpression, S context) {
rangeExpression.getStartExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
rangeExpression.getEndExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.TSQLLeftJoin tsqlLeftJoin, S context) {
tsqlLeftJoin.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
tsqlLeftJoin.getRightExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.TSQLRightJoin tsqlRightJoin, S context) {
tsqlRightJoin.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
tsqlRightJoin.getRightExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.StructType structType, S context) {
if ((structType.getArguments() != default!)) {
foreach (var selectItem in structType.getArguments()) {
selectItem.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
}
}
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.LambdaExpression lambdaExpression, S context) {
lambdaExpression.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.HighExpression highExpression, S context) {
highExpression.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.LowExpression lowExpression, S context) {
lowExpression.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Plus plus, S context) {
this.visitBinaryExpression(plus, " PLUS ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.PriorTo priorTo, S context) {
this.visitBinaryExpression(priorTo, " PLUS ");
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Inverse inverse, S context) {
inverse.getExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.TimeKeyExpression timeKeyExpression) {
this.visit<object>(timeKeyExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.DateTimeLiteralExpression literal) {
this.visit<object>(literal, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.NextValExpression nextVal) {
this.visit<object>(nextVal, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.CollateExpression col) {
this.visit<object>(col, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.SimilarToExpression expr) {
this.visit<object>(expr, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.ArrayExpression array) {
this.visit<object>(array, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.ArrayConstructor aThis) {
this.visit<object>(aThis, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.VariableAssignment a) {
this.visit<object>(a, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.TimezoneExpression a) {
this.visit<object>(a, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.XMLSerializeExpr xml) {
this.visit<object>(xml, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.JsonAggregateFunction expression) {
this.visit<object>(expression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.JsonFunction expression) {
this.visit<object>(expression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.ConnectByRootOperator connectByRootOperator) {
this.visit<object>(connectByRootOperator, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.OracleNamedFunctionParameter oracleNamedFunctionParameter) {
this.visit<object>(oracleNamedFunctionParameter, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.AllColumns allColumns) {
this.visit<object>(allColumns, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.AllTableColumns allTableColumns) {
this.visit<object>(allTableColumns, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.AllValue allValue) {
this.visit<object>(allValue, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.IsDistinctExpression isDistinctExpression) {
this.visit<object>(isDistinctExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.GeometryDistance geometryDistance) {
this.visit<object>(geometryDistance, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Statement.Select.Select select) {
this.visit<object>(select, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.TranscodingFunction transcodingFunction) {
this.visit<object>(transcodingFunction, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.TrimFunction trimFunction) {
this.visit<object>(trimFunction, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.RangeExpression rangeExpression) {
this.visit<object>(rangeExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.TSQLLeftJoin tsqlLeftJoin) {
this.visit<object>(tsqlLeftJoin, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.TSQLRightJoin tsqlRightJoin) {
this.visit<object>(tsqlRightJoin, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.StructType structType) {
this.visit<object>(structType, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.LambdaExpression lambdaExpression) {
this.visit<object>(lambdaExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.HighExpression highExpression) {
this.visit<object>(highExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.LowExpression lowExpression) {
this.visit<object>(lowExpression, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.Plus plus) {
this.visit<object>(plus, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Operators.Relational.PriorTo priorTo) {
this.visit<object>(priorTo, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.Inverse inverse) {
this.visit<object>(inverse, (object)default!);
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.CosineSimilarity cosineSimilarity, S context) {
cosineSimilarity.getLeftExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
cosineSimilarity.getRightExpression().accept<object, S>((global::DripSharp.SqlTrellis.Expression.ExpressionVisitor<object>)(this), context);
return default!;
}

public virtual object visit<S>(global::DripSharp.SqlTrellis.Statement.Piped.FromQuery fromQuery, S context) {
return default!;
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.ConnectByPriorOperator connectByPriorOperator) {
this.visit<object>(connectByPriorOperator, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.OracleHint hint) {
this.visit<object>(hint, (object)default!);
}

public virtual void visit<TWildcard0_0>(global::DripSharp.SqlTrellis.Expression.RowConstructor<TWildcard0_0> rowConstructor) where TWildcard0_0 : global::DripSharp.SqlTrellis.Expression.Expression {
this.visit<object, TWildcard0_0>(rowConstructor, (object)default!);
}

public virtual void visit(global::DripSharp.SqlTrellis.Expression.RowGetExpression rowGetExpression) {
this.visit<object>(rowGetExpression, (object)default!);
}

public virtual void visit<TWildcard0_0>(global::DripSharp.SqlTrellis.Expression.Operators.Relational.ExpressionList<TWildcard0_0> expressionList) where TWildcard0_0 : global::DripSharp.SqlTrellis.Expression.Expression {
this.visit<object, TWildcard0_0>(expressionList, (object)default!);
}
}
