// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/validator/LimitValidator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Validator;

public class LimitValidator : global::DripSharp.SqlTrellis.Util.Validation.Validator.AbstractValidator<global::DripSharp.SqlTrellis.Statement.Select.Limit> {
public override void validate(global::DripSharp.SqlTrellis.Statement.Select.Limit limit) {
foreach (global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability c in this.getCapabilities()) {
this.validateFeature(c, global::DripSharp.SqlTrellis.Parser.Feature.Feature.limit);
this.validateFeature(c, limit.isLimitNull(), global::DripSharp.SqlTrellis.Parser.Feature.Feature.limitNull);
this.validateFeature(c, limit.isLimitAll(), global::DripSharp.SqlTrellis.Parser.Feature.Feature.limitAll);
this.validateOptionalFeature(c, limit.getOffset(), global::DripSharp.SqlTrellis.Parser.Feature.Feature.limitOffset);
}
}
}
