// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/validator/ShowColumnsStatementValidator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Validator;

public class ShowColumnsStatementValidator : global::DripSharp.SqlTrellis.Util.Validation.Validator.AbstractValidator<global::DripSharp.SqlTrellis.Statement.ShowColumnsStatement> {
public override void validate(global::DripSharp.SqlTrellis.Statement.ShowColumnsStatement show) {
this.validateFeatureAndName(global::DripSharp.SqlTrellis.Parser.Feature.Feature.showColumns, global::DripSharp.SqlTrellis.Util.Validation.Metadata.NamedObject.table, show.getTableName());
}
}
