// <auto-generated />
// Mechanically translated from: net/sf/jsqlparser/util/validation/validator/UpdateValidator.java
// Upstream repository: https://github.com/JSQLParser/JSqlParser.git
// Upstream revision: 8a9479a05c75fcb73d0ed167a822b9b18ab7abaa
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: upstream supplies no NOTICE file.
#nullable disable
namespace DripSharp.SqlTrellis.Util.Validation.Validator;

public class UpdateValidator : global::DripSharp.SqlTrellis.Util.Validation.Validator.AbstractValidator<global::DripSharp.SqlTrellis.Statement.Update.Update> {
public override void validate(global::DripSharp.SqlTrellis.Statement.Update.Update update) {
foreach (global::DripSharp.SqlTrellis.Util.Validation.ValidationCapability c in this.getCapabilities()) {
this.validateFeature(c, global::DripSharp.SqlTrellis.Parser.Feature.Feature.update);
this.validateOptionalFeature(c, update.getFromItem(), global::DripSharp.SqlTrellis.Parser.Feature.Feature.updateFrom);
this.validateOptionalFeature(c, global::DripSharp.Runtime.JavaCompat.CastObjects(update.getStartJoins()), global::DripSharp.SqlTrellis.Parser.Feature.Feature.updateJoins);
this.validateFeature(c, update.isUseSelect(), global::DripSharp.SqlTrellis.Parser.Feature.Feature.updateUseSelect);
this.validateOptionalFeature(c, global::DripSharp.Runtime.JavaCompat.CastObjects(update.getOrderByElements()), global::DripSharp.SqlTrellis.Parser.Feature.Feature.updateOrderBy);
this.validateOptionalFeature(c, update.getLimit(), global::DripSharp.SqlTrellis.Parser.Feature.Feature.updateLimit);
this.validateOptionalFeature(c, global::DripSharp.Runtime.JavaCompat.CastObjects(update.getReturningClause()), global::DripSharp.SqlTrellis.Parser.Feature.Feature.updateReturning);
}
this.validateOptionalFromItem(update.getTable());
this.validateOptional<global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.Join>>(update.getStartJoins(), (j) => this.getValidator<global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator>(typeof(global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator)).validateOptionalJoins(j));
if (update.isUseSelect()) {
this.validateOptionalExpressions(update.getColumns());
this.validateOptional<global::DripSharp.SqlTrellis.Statement.Select.Select>(update.getSelect(), (e) => e.accept<object, object>((global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<object>)((global::DripSharp.SqlTrellis.Statement.Select.SelectVisitor<object>)(this.getValidator<global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator>(typeof(global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator))!)), (object)default!));
} else {
this.validateOptionalExpressions(update.getColumns());
this.validateOptionalExpressions(update.getExpressions());
}
if ((update.getFromItem() != default!)) {
this.validateOptionalFromItem(update.getFromItem());
this.validateOptional<global::System.Collections.Generic.IList<global::DripSharp.SqlTrellis.Statement.Select.Join>>(update.getJoins(), (j) => this.getValidator<global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator>(typeof(global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator)).validateOptionalJoins(j));
}
this.validateOptionalExpression(update.getWhere());
this.validateOptionalOrderByElements(update.getOrderByElements());
if ((update.getLimit() != default!)) {
this.getValidator<global::DripSharp.SqlTrellis.Util.Validation.Validator.LimitValidator>(typeof(global::DripSharp.SqlTrellis.Util.Validation.Validator.LimitValidator)).validate(update.getLimit());
}
if ((update.getReturningClause() != default!)) {
global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator v = this.getValidator<global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator>(typeof(global::DripSharp.SqlTrellis.Util.Validation.Validator.SelectValidator));
global::DripSharp.Runtime.JavaCompat.ForEach(update.getReturningClause(), (c) => c.accept<object, object>((global::DripSharp.SqlTrellis.Statement.Select.SelectItemVisitor<object>)(v), (object)default!));
}
}
}
